broadinstitute/sherlock

internal/environments/environments.go, internal/environments/environments_test.go, internal/environments/models.go, internal/testutils/integrationHelpers.go, internal/testutils/seed.go
POC PR, still needs some more tests to be fully tested,
There are 2 types of tests, one is using a "testCases" format (CreateEnvironment), the other is using a more freeform format, not sure what's better atm.
=> Ddo 1521 environment integrations tests

internal/allocationpools/allocation_pools_test.go, internal/allocationpools/models.go
Updated the tests to use the Rollback/Begin the other tests use, but it seems to still have issues, not sure whats going on.
=> added transactions to allocation_pools_tests

internal/controllers/v2controllers/app_version_test.go, internal/controllers/v2controllers/chart_deploy_record_test.go, internal/controllers/v2controllers/chart_release_test.go, internal/controllers/v2controllers/chart_test.go, internal/controllers/v2controllers/chart_version_test.go, internal/controllers/v2controllers/cluster_test.go, internal/controllers/v2controllers/environment_test.go, internal/controllers/v2controllers/model_controller.go
See https://github.com/broadinstitute/sherlock/pull/60/files#diff-8335575066a4ac3f4429b224e9b0f58a12e6f63c0d0e0b395bb16ea710e54c7f for the actual change here; the rest of the diff is added tests
=> [DDO-2296] Make list endpoints return empty instead of nil

db/migrations/000017_add_url_fields.down.sql, db/migrations/000017_add_url_fields.up.sql, internal/controllers/v2controllers/chart.go, internal/controllers/v2controllers/chart_release.go, internal/controllers/v2controllers/chart_release_test.go, internal/controllers/v2controllers/chart_test.go, internal/controllers/v2controllers/environment.go, internal/controllers/v2controllers/environment_test.go, internal/models/v2models/chart.go, internal/models/v2models/chart_release.go, internal/models/v2models/environment.go
Basically https://github.com/broadinstitute/thelma/pull/27/files#diff-a14c13a906ee5904378d513aa15bc603ccad0f7a72b7b711cbc0eafeaae1768a but now supported directly by Sherlock. Works with editing and templating as expected.
=> [DDO-2337] Add URL fields from terra-helmfile

internal/models/v2models/chart_release.go, internal/models/v2models/chart_release_test.go
Diff does a good job explaining what's changing here--I already had unit tests for the exact behavior here
=> [DDO-2368] Report ChartRelease name first when there's a conflict on it

.github/workflows/client-report-app-version.yaml
I've actually been using this branch in Beehive for a while, time to get this merged in. We might move this workflow out of this repo at some point but no reason to let the used thing sit on a branch.
=> [DDO-2415] Tweaks to the new app version GHA

README.md
This repo gets linked to from a bunch of places now, should update this
=> [DDO-2515] Update README.md

.github/workflows/client-refresh-environment.yaml
This might not get much usage but WSM needs it and I think it is a reasonable thing to have. Requires https://github.com/broadinstitute/terra-github-workflows/pull/47
=> [DDO-2520] Add a client-refresh-environment workflow

.github/workflows/client-refresh-environment.yaml
What I get for copy-pasting, my bad
=> [DDO-2520] Fix typo in the comment

.github/workflows/client-refresh-environment.yaml
- Correctly reference the get env
- Handle the secret conditional correctly
- Include the refresh flag
=> [DDO-2525] Fix client-refresh-environment

internal/metrics/v2metrics/metrics.go, internal/models/v2models/metrics_updater.go
She said a summary of what apps are using fc-dev would be helpful for her. That info is in Sherlock so... *make it so*.
=> [DDO-2573] Add a fc-dev usage metric for Ambica

.github/workflows/client-report-app-version.yaml
=> Quote shell parameter

config/default_config.yaml, internal/pagerduty/send_alert.go, internal/pagerduty/send_change.go
I thought this wouldn't panic but apparently it does. :/
=> [DDO-2593] Fix panic when sending a short pagerduty alert

internal/models/v2models/environment.go, internal/models/v2models/environment_test.go
Maybe I could do better here but length and some format is already enforced as the name is a selector. Not trying to step on that here, just to make this part better.
=> Check environment names against regex

.github/workflows/client-refresh-environment.yaml
https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/4340531569/jobs/7579164824
=> [DDO-2706] Fix refresh-environment client workflow

.github/workflows/client-refresh-environment.yaml
=> [DDO-2747] Additional workflow-dispatch fix

internal/handlers/v2handlers/chart.go, internal/handlers/v2handlers/database_instance.go, internal/handlers/v2handlers/user.go
Comment-only change to fix the OpenAPI spec for the PUT requests, it's functionally fine but there's a parameter I copy-pasted wrong
=> [DDO-2757] Fix OpenAPI spec

sherlock/internal/boot/liveness/server.go
Forgot to push a commit on #210 
Adds mutex wrapping around a non-goroutine/non-async usage of `s.handler.returnOK` just because it's the right thing to do and improves the comment for the struct at the top of the file.
=> [DDO-2976] Improve mutex usage and comment

sherlock-webhook-proxy/pkg/handler.go
Swap out the method being used from the client library. The new one doesn't require a "selector" input and it won't ever return an "edited" indication (it always creates).
I ran the full chain of webhook receiver -> cloud function code -> sherlock locally to validate that this works
None IMO
=> [DDO-2985] Make the GHA webhook proxy use the new endpoint

sherlock/internal/authorization/firecloud_suitability_cache.go
So I made a bad assumption when I did some of Sherlock's refactor. I assumed that when we created Google Workspace accounts and specified the secondary email, we were specifying the recovery email. That'd mean that I could use the Google Workspace client library's `User.RecoveryEmail` field to grab the user's email, in a more secure way that doing string replacement on email suffixes.
I was wrong! Turns out they're totally different. Secondary email is only visible in the, uh, _untyped_ `User.Emails` field.
I still think that using this is better than doing string replacement on email suffixes, because that way breakglass accounts etc don't get spurious entries added for them. This PR adds a few lines of code that does a dumb hack: `User.Emails`'s `interface{}` -> JSON marshal to `[]byte` …
=> [DDO-3004] Fix Sherlock's understanding of secondary firecloud.org emails

sherlock/db/migrations/000046_chart_v3.down.sql, sherlock/db/migrations/000046_chart_v3.up.sql, sherlock/internal/deprecated_controllers/v2controllers/chart_test.go, sherlock/internal/models/chart.go, sherlock/internal/models/chart_test.go
Not exposed in the API yet, just taking baby steps.
Tests added, including for the added SQL checks.
None
=> [DDO-3011] v3 Chart model

foundation.yaml
- add foundation.yaml
- more foundation metadata experimentation
=> More Foundation metadata file experimentation

.github/workflows/sherlock-build.yaml
I managed to mess up my merge when Eno merged so mine didn't work. Retries don't work because of conflicts in the generated files. This is the easiest way to get my change out the door, I just don't feel like spending a day trying to improve the build GHA.
Can't, except for it running in this PR.
Repo CI, no risk to anything running.
=> [DDO-3035] Allow manual invocation of sherlock-build

foundation.yaml
More experimentation with what is possible in backstage metadata files.
=> Add sherlock client libs and database into backstage

sherlock/config/default_config.yaml, sherlock/internal/db/connect.go
https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1692116090451579
=> [DDO-3039] Set max idle connections to a high value to make Sherlock less aggressive with the cloud sql proxy

sherlock/internal/db/connect.go
https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1692120348275669?thread_ts=1692116090.451579&cid=CQ6SL4N5T
=> [DDO-3039] Let max times be set to 0

sherlock/config/default_config.yaml, sherlock/db/migrations/000050_add_dispatched_at.down.sql, sherlock/db/migrations/000050_add_dispatched_at.up.sql, sherlock/internal/models/app_version.go, sherlock/internal/models/chart.go, sherlock/internal/models/chart_release.go, sherlock/internal/models/chart_test.go, sherlock/internal/models/chart_version.go, sherlock/internal/models/ci_run.go, sherlock/internal/models/ci_run_test.go, sherlock/internal/models/cluster.go, sherlock/internal/models/environment.go
Helper functions in the models package that I'm now using in the Slack deploy hook code.
The two additions are CiRun.WebURL (generates a link to the CiRun) and CiRun.Succeeded (bool if it was a success). There's also a (currently unused) field being added to CiRun.
Tests for the new functions. Not used by any existing part of Sherlock.
None
=> [DDO-3046] Model-level improvements to prepare for Slack deploy hooks

sherlock/internal/deprecated_controllers/v2controllers/changeset_procedures.go, sherlock/internal/deprecated_controllers/v2controllers/changeset_test.go
As discussed in extemp
Wrote tests for both behaviors
Very low, test coverage on both sides of the added code
=> [DDO-3047] Don't promote helmfile ref by default anymore

sherlock/internal/deployhooks/dispatch_slack_deploy_hook.go, sherlock/internal/deployhooks/dispatch_slack_deploy_hook_test.go
Goes from this:
> Deployment to dev: [success](https://github.com/broadinstitute/terra-github-workflows/actions/runs/5904887278/attempts/1). Review all changes made by this deployment [here](https://beehive.dsp-devops.broadinstitute.org/review-changesets?changeset=389019).
To this:
> Deployment to [dev](https://beehive.dsp-devops.broadinstitute.org/environments/dev) ([bond-dev](https://beehive.dsp-devops.broadinstitute.org/environments/dev/chart-releases/bond)): [success](https://github.com/broadinstitute/terra-github-workflows/actions/runs/5904887278/attempts/1). Review all changes made by this deployment [here](https://beehive.dsp-devops.broadinstitute.org/review-changesets?changeset=389019).
It'll comma-separate if there's multiple.
100% test coverage on this change 🎉 
None
=> [DDO-3050] Improve links in Slack deploy hook messages

sherlock/internal/db/connect.go
This reverts commit 18297a3a59426b8017c7e869862f1416960f25cf.
=> Revert "[DDO-3048] Disable prepared statements cache (#257)"

sherlock/internal/deprecated_models/v2models/changeset.go
I don't have the time or energy to write a bunch about what this does or why it temporarily alleviates the issue. I'm not in a wonderful spot to keep working and just want to stem the bleeding so I can pick this up tomorrow.
=> [DDO-3058] Try to hack around Gorm's upsert logic

sherlock/internal/api/sherlock/ci_runs_procedures_v3_github_info_list.go, sherlock/internal/api/sherlock/ci_runs_procedures_v3_github_info_list_test.go, sherlock/internal/api/sherlock/routes.go
This will be really helpful for Beehive.
It returns data like this:
```json
{
"CancerDataAggregator": {
"cda-service": [
".github/workflows/pr_push.yml",
".github/workflows/tests.yml",
".github/workflows/trivy.yaml",
".github/workflows/master_push.yml"
]
},
"DataBiosphere": {
"biocore-data-model": [
".github/workflows/build.yaml"
],
"calhoun": [
".github/workflows/unit-test.yml",
".github/workflows/trivy.yml",
".github/workflows/build.yml"
],
```
Added tests
None
=> [DDO-3075] Expose Sherlock's knowledge of repos and workflow files

.github/workflows/sherlock-build.yaml
This reverts commit c8b472e8ab2e4a716ff02d8dd440763255e86de2.
=> Revert "add more tags"

sherlock/internal/pactbroker/record_deployment.go
Summary:
Logging the request URL that's causing a 404.
=> DDO-3312 Return pact URL in log

sherlock/internal/deprecated_models/v2models/changeset.go
As discussed in https://broadinstitute.slack.com/archives/CADM7MZ35/p1702566334159059?thread_ts=1702562945.057629&cid=CADM7MZ35
=> [DDO-3385] Disable Pact code pending test coverage

sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit.go, sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit_test.go
Well I did so much testing that the flagged code wouldn't run that I didn't actually check that the flag could be positively set. This PR does that and adds a test for it. 🙃 
Augments the existing edit test
None
=> [DDO-3400] Fix feature flag for Slack deploy hooks

sherlock/internal/slack/deployment_notification.go
When there's an error sending blocks, it now logs them. Should help with [this](https://broadinstitute.slack.com/archives/C011NQS8Q2Z/p1704398175644989)
None but it just logs and this is in the broken code anyway
Very low (panic-protected, too)
=> [DDO-3400] Improve logging for `invalid_blocks` Slack errors

sherlock/internal/hooks/slack_deploy_hook.go, sherlock/internal/models/app_version.go, sherlock/internal/models/changeset.go, sherlock/internal/models/chart_version.go, sherlock/internal/slack/escape.go
A bunch of tiny tweaks, it's mostly working which is neat
=> [DDO-3400] Bunch of message tweaks

makefile
https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1704408655616939
=> [DDO-3403] Allow Sherlock to receive webhooks from the hcholab GitHub org

sherlock/internal/hooks/slack_deploy_hook.go
ArgoCD or Kubernetes (not sure which, doesn't really matter) return snippets like "1/3" or "1 out of 3" which Sherlock parses to mean 33%, for example. I was handling the "1/3" case but not the "1 out of 3" case, this PR fixes that
=> [DDO-3400] Fix parsing of ArgoCD fractions

sherlock/internal/api/sherlock/git_commits_v3_upsert.go
Include some more info in the errors, which should help us figure out what's going on
=> [DDO-3421] Log more about git commit errors

.github/workflows/sherlock-api-diff.yaml
I messed up #437 by just totally mixing up base and head in my brain, I removed the wrong one and tested in the wrong direction. I didn't read my own comment that would've helped me either.
=> [DDO-3422] Better *head* ref

sherlock/internal/api/sherlock/git_commits_v3_upsert.go
no negative values for timeSince
=> DDO-3377: Git Commit error handling

sherlock/db/migrations/000073_add_incidents.down.sql, sherlock/db/migrations/000073_add_incidents.up.sql, sherlock/internal/api/sherlock/incidents_v3.go, sherlock/internal/api/sherlock/incidents_v3_create.go, sherlock/internal/api/sherlock/incidents_v3_create_test.go, sherlock/internal/api/sherlock/incidents_v3_delete.go, sherlock/internal/api/sherlock/incidents_v3_delete_test.go, sherlock/internal/api/sherlock/incidents_v3_edit.go, sherlock/internal/api/sherlock/incidents_v3_edit_test.go, sherlock/internal/api/sherlock/incidents_v3_get.go, sherlock/internal/api/sherlock/incidents_v3_get_test.go, sherlock/internal/api/sherlock/incidents_v3_list.go, sherlock/internal/api/sherlock/incidents_v3_list_test.go, sherlock/internal/api/sherlock/incidents_v3_test.go, sherlock/internal/api/sherlock/routes.go, sherlock/internal/models/incident.go, sherlock/internal/models/test_data.go
Does what it says on the tin. Fully tested. No metrics yet. https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1706040278042629?thread_ts=1706040042.001309&cid=CQ6SL4N5T
Yes
No
=> [DDO-3447] Add incident API (no metrics yet)

sherlock/internal/api/sherlock/environments_v3_delete.go, sherlock/internal/api/sherlock/environments_v3_delete_test.go, sherlock/internal/api/sherlock/routes.go
DELETE environment, refactored (the actual logic here has already been tested, we just care about wiring the endpoint correctly)
Tests for deletion, deletion protection, and suitability
Low
=> [DDO-3449] Environment delete, v3

sherlock/internal/api/sherlock/chart_releases_v3_delete.go, sherlock/internal/api/sherlock/chart_releases_v3_delete_test.go, sherlock/internal/api/sherlock/routes.go
Like #456 but for chart releases
Added test file
Low
=> [DDO-3449] Chart Release v3 delete

sherlock/internal/api/sherlock/environments_v3_edit.go, sherlock/internal/api/sherlock/environments_v3_edit_test.go, sherlock/internal/api/sherlock/routes.go
Just to be clear I kinda wrote these beforehand and I'm just trying to get in the habit of making smaller PRs
Like #456 but for edit
Test file added
Low (environment edits aren't complex)
=> [DDO-3449] Environment v3 edit

sherlock/internal/api/sherlock/chart_releases_v3_edit.go, sherlock/internal/api/sherlock/chart_releases_v3_edit_test.go, sherlock/internal/api/sherlock/routes.go
Last one of this chain, I think
Test file added
Low
=> [DDO-3449] Chart Release v3 edit

sherlock/db/migrations/000075_fix_database_instance_v3.down.sql, sherlock/db/migrations/000075_fix_database_instance_v3.up.sql, sherlock/internal/api/sherlock/database_instances_v3.go, sherlock/internal/api/sherlock/database_instances_v3_create.go, sherlock/internal/api/sherlock/database_instances_v3_create_test.go, sherlock/internal/api/sherlock/database_instances_v3_delete.go, sherlock/internal/api/sherlock/database_instances_v3_delete_test.go, sherlock/internal/api/sherlock/database_instances_v3_edit.go, sherlock/internal/api/sherlock/database_instances_v3_edit_test.go, sherlock/internal/api/sherlock/database_instances_v3_get.go, sherlock/internal/api/sherlock/database_instances_v3_get_test.go, sherlock/internal/api/sherlock/database_instances_v3_list.go, sherlock/internal/api/sherlock/database_instances_v3_list_test.go, sherlock/internal/api/sherlock/database_instances_v3_test.go, sherlock/internal/api/sherlock/routes.go, sherlock/internal/models/database_instance_test.go, sherlock/internal/models/environment.go
create, edit, list, get, and delete for v3 database instances
also fixed some missing duplicate validation and fixed a bug with duplication that it revealed
New file for each route and for the data type itself
Very low
=> [DDO-3449] Database Instance, v3 methods

sherlock/internal/api/sherlock/pagerduty_integrations_procedures_v3_trigger_incident.go, sherlock/internal/api/sherlock/pagerduty_integrations_procedures_v3_trigger_incident_test.go, sherlock/internal/api/sherlock/pagerduty_integrations_v3_get.go, sherlock/internal/api/sherlock/routes.go, sherlock/internal/deprecated_controllers/v2controllers/model_controller.go, sherlock/internal/pagerduty/send_alert.go
Simple procedure method I forgot to port over. I'm changing it to make the source URL configurable from the caller's end.
Added a new test file
Very low
=> [DDO-3470] Add missing "trigger pagerduty incident" method

sherlock/internal/api/sherlock/github_actions_jobs_v3_upsert.go
I put 200 rather than 201, my bad, but if I don't fix it now then it'll be kinda a pain to fix later.
=> [DDO-3577] Fix new API status code

sherlock-webhook-proxy/pkg/handler.go
Add another case to the proxy function to handle these payloads. I need a field that the library doesn't parse, so I had to copy the bytes to parse it out myself. I did test this end-to-end locally with the instructions in the readme.
=> [DDO-3577] Have proxy handle `workflow_job` payloads=

sherlock/config/default_config.yaml
Replaces hostname and namespace references for the new ArgoCD instance
=> [DDO-3527] Cut over ArgoCD

sherlock/internal/api/sherlock/ci_runs_v3_upsert.go, sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
...this way, if someone clicks "retry failed jobs", they'll still get retry notification channels from the already-completed-and-won't-rerun call to https://github.com/broadinstitute/sherlock/blob/main/.github/workflows/client-report-workflow.yaml
Added a unit/mocked test case expanding on the issue @okotsopoulos and @rushtong brought up in Slack
Very low
=> [DDO-3623] Inherit retry notification channels from previous runs

.github/workflows/sherlock-build.yaml
Like https://github.com/broadinstitute/thelma/pull/279 but for Sherlock.
=> [DDO-3622] Publish images to super-prod GAR

CONTRIBUTING.md
Adding a WIP doc to satisfy new service checklist requirements
=> [DDO-3641 `CONTRIBUTING.md`

CONTRIBUTING.md
=> [DDO-3641] Note ticket requirement in `CONTRIBUTING.md`

sherlock/internal/suitabilityloader/sync_to_db.go
The suitability table in Sherlock is working, but as acknowledged in the comment there's a gap -- we need to have some way of _removing_ records when the external sources do (e.g. if someone's entire firecloud.org account was deleted, we'd want their suitability record to evaporate too).
Looking at prod, it's clear that Gorm does _not_ set the updated_at field on the record if no actual update occurred. That's fine: we'll set it ourselves.
We add a deletion statement too, that uses "three times the normal update interval ago" as the cut-off point. Is it ugly? Yes. Will this code exist for a week or two? Also yes.
Manual, worked locally. The reason to do this in a separate PR is we'll be able to inspect prod to know that the table looks right before using it, too.
Low
=> [DDO-3673] Persistent suitability, now with deletion of removed records

sherlock/internal/suitability_loader/sync_to_db.go
See https://broadinstitute.slack.com/archives/CADM7MZ35/p1719608453224929
Sherlock will detect the dailyLimitExceeded error string, log the error, but move on, allowing Sherlock to boot and operate normally. It will continue to rely on it's cache of suitability data that it stores in the database
=> [DDO-3765] Absorb Google Workspace Directory API Quota Issues

sherlock/db/migrations/000093_auto_assign.down.sql, sherlock/db/migrations/000093_auto_assign.up.sql, sherlock/internal/api/sherlock/roles_v3.go, sherlock/internal/api/sherlock/roles_v3_test.go, sherlock/internal/boot/application.go, sherlock/internal/models/role.go, sherlock/internal/models/role_auto_assign.go, sherlock/internal/models/role_auto_assign_test.go, sherlock/internal/models/test_data.go
Adds a boolean field to Role that will have Sherlock automatically assign users to it. It respects Role.suspendNonSuitableUsers.
Tests for both cases of Role.suspendNonSuitableUsers
Low, Sarah G signed off on the idea and the implementation via API field
=> [DDO-3784] Add Role.autoAssignAllUsers

sherlock/internal/firecloud_account_manager/suspend_accounts.go, sherlock/internal/firecloud_account_manager/suspend_accounts_test.go
Rather than the last login time field being empty, null, or Go's zero time, it's the 0 unix timestamp encoded as RFC 3339. Bummer.
So the Firecloud account manager logic has been reworked. Rather than deciding whether a user has logged in or not to determine which threshold to apply to them, we always apply the grace period threshold and then go to the inactivity threshold. This means we can detect inactive accounts and accounts that have never logged in separately (for good notification output).
Tests updated
Low -- this behavior is fully captured by tests and we have confirmation that the dry-run capability works as intended. It's a sensitive part of the code but we have strong mitigations
=> [DDO-3860] Detect Firecloud accounts that have never logged in

sherlock/config/default_config.yaml, sherlock/config/test_config.yaml, sherlock/go.mod, sherlock/go.sum, sherlock/internal/config/config.go, sherlock/internal/config/retry.go, sherlock/internal/config/retry_test.go, sherlock/internal/firecloud_account_manager/suspend_accounts.go, sherlock/internal/firecloud_account_manager/suspend_accounts_test.go, sherlock/internal/role_propagation/propagator_propagate.go, sherlock/internal/role_propagation/propagator_propagate_test.go
Implements retries for the things that keep spamming us. Regexes given in config. Uses the same library as Thelma.
Config reading tested, mocked tests adjusted to rely on retry behavior.
Low? Worst case it somehow handles errors worse. Even panics would be recovered from.
=> [DDO-3864] Add retries
