broadinstitute/sherlock

internal/builds/builds.go
internal/builds/handlers.go
internal/builds/handlers_test.go
internal/builds/models.go
internal/builds/serializers.go
internal/services/handlers.go
internal/services/handlers_test.go
internal/services/mocks.go
internal/services/models.go
internal/services/serializers.go
internal/services/services.go
internal/sherlock/sherlock_integration_test.go
internal/tools/seed.go

This pr was inspired by @choover-broad 's comment [here](https://github.com/broadinstitute/sherlock/pull/8#discussion_r708553219). The goal here is to create serializers to convert the model type for Sherlock's entities to a type that is used generate http response bodies. 
This means that the DB model type is now fully decoupled from requests and responses. This is important for giving us more granular control over what information we show in these api responses. This also makes it easier to hide implementation details and support backwards compatibility if needed.
These changes are based on [this pattern](https://github.com/gothinkster/golang-gin-realworld-example-app/blob/master/articles/serializers.go) from the gin example repo.

DDO-1532 Serializers for service and build responses

---

internal/builds/models.go
internal/tools/seed.go

In gorm models `CreatedAt` and `UpdatedAt` fields have special magic going on behind the scenes where it will set those timestamps to the current time in postgres unless they are specified ie non-zero value for `time.Time` . To get this same behavior for other timestamp columns such as built at requires a special `gorm` struct tag. This will guarantee that `built_at` column is set to current time when a new build is created if it is not otherwise specified. 
The behavior without this is that a Zero value for go's `time.Time` would be persisted to Postgres in the `built_at` column which can cause non-deterministic results. [Relevant documentation](https://gorm.io/docs/models.html#Creating-Updating-Time-Unix-Milli-Nano-Seconds-Tracking)

[No Ticket] Fix Bug in BuiltAt timestamp field

---

.github/workflows/test.yaml
build/local/server/docker-compose.test.yaml
build/server/Dockerfile.test
internal/sherlock/sherlock_integration_test.go
makefile

This  PR aims to address the race condition issue that I mentioned in standup that started popping up in the sherlock integration test suite. Part of what made this issue so difficult to debug was that go's testing tool was being invoked with different configuration in local environments vs the gitub actions pipeline.
Now the integration tests will be executed in a consistent manner both in GHA and on developer machines.
Additionally my initial experimental approach to integration testing `sherlock_integration_testing.go` has outgrown it's original scope as it has proven to be an untenable pattern for testing as the application grows in scope and complexity and is now leaking side effects into other tests. 
As such I'm commenting out that file for now and will break up testing the same …

Mitigating Race Condition issue in Github Actions Workflow

---

db/migrations/000009_add_unique_contstraint_to_service_instances.down.sql
db/migrations/000009_add_unique_contstraint_to_service_instances.up.sql
internal/deploys/mocks.go
internal/deploys/models.go
internal/deploys/serviceInstance.go
internal/deploys/serviceInstance_test.go
internal/environments/environments.go
internal/environments/environments_test.go
internal/services/services.go
internal/services/services_test.go
makefile

This PR implements the remaining `ServiceInstance` aka association between service and environment, needed for accelerate metrics. There are two key functionalities implemented here:
1. The ability to create new service instances. This functionality performs a check to make sure that both the service and environment exist and will create them if not before actually persisting the association to the `service_instances` table. To facilitate this functionality `FindOrCreate` methods were added to both the services and environments controllers. The combination of service and environment together are required to be unique
2. The ability to look up service instances given the environment and service names, this is a critical functionality for the eventual `deploys` route handlers.
This PR does …

DDO-1564 Complete Necessary functionality for service instances

---

db/migrations/000010_add_missing_build_id_to_deploys.down.sql
db/migrations/000010_add_missing_build_id_to_deploys.up.sql
db/migrations/000011_add_versionstring_idx_to_builds.down.sql
db/migrations/000011_add_versionstring_idx_to_builds.up.sql
internal/builds/builds.go
internal/builds/builds_test.go
internal/builds/handlers_test.go
internal/builds/models.go
internal/deploys/deploys.go
internal/deploys/deploys_test.go
internal/deploys/mocks.go
internal/deploys/models.go
internal/deploys/serviceInstance.go
internal/deploys/serviceInstance_test.go
internal/environments/environments_test.go
internal/services/services_test.go
internal/testutils/integrationHelpers.go
makefile

Ok, so there is a bit of chonk here as implementing the core functionality for this ticket exposed some issues in our integration test suite. 
This PR essentially does 2 things.
1. It implements the core control plane functionality to track deploy entities. These are the essential component to calculating accelerate metrics. They are essentially an association between a service, environment, and build version at a point in time. It is this functionality that will be instrumented to track metrics like deploy frequency and lead time to prod.
2. The deploy tracking functionality involves some more heavyweight database operations. This exposed some previously unnoticed database race conditions in our integration test suite. This pr also fixes those data base race conditions. It accomplishes …

DDO-1564 Create New Deploys and List Deploy History for Service/Environment Control Plane Functionality

---

internal/cli/createBuild.go
internal/cli/createDeploy.go
internal/cli/createDeploy_test.go
internal/cli/deploys.go
internal/cli/root.go
internal/testutils/integrationHelpers.go

This pr implements the `sherlock deploys create` functionality in sherlock's cli interface. This is essentially a POST to sherlock's `deploys/:environment/:service` endpoint.

DDO-1602 CLI command for creating deploys

---

build/local/server/docker-compose.yaml
internal/sherlock/sherlock.go
internal/testutils/integrationHelpers.go
makefile

The default of `postgres` as the host value in the postgres connection string was set to support some now deprecated patterns in sherlock's development. Setting a sane default of `localhost` instead since that is what the integration testing tooling and cloudsql proxy use.

[No Ticket] Set Sane Default for the host value in DB connection config

---

internal/deploys/deploys.go
internal/deploys/handlers.go
internal/deploys/models.go

Previously sherlock was increasing lead time artificially when the same build was deployed to an environment multiple times in a row by recalculating the time diff between image creation and current deploy time for each redeploy. This PR adds a check so that lead time will only be updated if a new build version is being deployed. These re-deploy events are still recorded in sherlock's db and count towards deploy frequency.

DDO-1684 Fix for Artificially increasing lead times

---

codecov.yaml

The generated client libs are going to destroy our codecoverage stat without this.

Update Codecov to ignore dir with generated clients

---

.github/workflows/gen-swagger.yaml
internal/handlers/v2handlers/app_version.go
internal/handlers/v2handlers/chart.go
internal/handlers/v2handlers/chart_deploy_record.go
internal/handlers/v2handlers/chart_release.go
internal/handlers/v2handlers/chart_version.go
internal/handlers/v2handlers/cluster.go
internal/handlers/v2handlers/environment.go

Updates the swagger spec so that the fact that successful POST requests to v2 endpoints return status `201` rather than `200`.
Also adds CI support for building and publishing the go client library based on the generated swagger spec upon merge to main.

DDO-2264 Fix POST status annotation and add ci for client lib generation

---

.github/workflows/gen-swagger.yaml

I'm really not too concerned about trying to standardize on a tool here.
It makes the TypeScript library at `clients/typescript-fetch` and the Go library at `go-openapi-generator` just for now so we can compare.

Generate Typescript (and Go) from openapi-generator

---

internal/controllers/v2controllers/cluster.go

This is enforced (there's a test for it) internally, and at the Swagger level it's actually bad because it prevents us from listing all clusters. At one point I'd tried to remove all the validate struct tags and must have just missed one.

[DDO-2295] Cluster name presence accidentally enforced by Swagger

---

internal/controllers/v2controllers/README.md
internal/controllers/v2controllers/app_version.go
internal/controllers/v2controllers/chart_deploy_record.go
internal/controllers/v2controllers/chart_deploy_record_test.go
internal/controllers/v2controllers/chart_release.go
internal/controllers/v2controllers/chart_version.go
internal/controllers/v2controllers/environment.go

(Actually, just don't try to parse nested info structs from query parameters at all).
H/T to https://github.com/gin-gonic/gin/pull/1733 for an absolute life-saver here. The struct tags like this will ignore even _trying_ to bind nested structs out of query parameters so we won't hit that fun stack-overflow issue.
Granted I'm, uh, not super sure how on earth to test this. The stack overflow comes up in Gin, from binding in handlers, in a way that the current v2 test infra doesn't really let us check. We'd have to spin up a very full Sherlock server and hit it for tests and I think that's not worth it here.

[DDO-2308] Don't recursively parse query parameters

---

db/migrations/000018_add_exposes_endpoint.down.sql
db/migrations/000018_add_exposes_endpoint.up.sql
internal/controllers/v2controllers/chart.go
internal/controllers/v2controllers/chart_release.go
internal/controllers/v2controllers/chart_release_test.go
internal/controllers/v2controllers/chart_test.go
internal/controllers/v2controllers/environment_test.go
internal/models/v2models/chart.go

Just a little default-false field to indicate whether the "defaultSubdomain" etc fields actually matter. This gets passed down to influence chart release creation, so if this is false then the defaultSubdomain etc won't get put into the chart release's subdomain etc field. This gives Beehive enough information to know whether to show the URL in the UI.

[DDO-2339] Add "chartExposesEndpoint" field to Charts

---

db/migrations/000019_add_version_descriptions.down.sql
db/migrations/000019_add_version_descriptions.up.sql
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/v2controllers/app_version.go
internal/controllers/v2controllers/app_version_test.go
internal/controllers/v2controllers/chart_version.go
internal/controllers/v2controllers/chart_version_test.go
internal/handlers/v2handlers/app_version.go
internal/handlers/v2handlers/chart_version.go
internal/models/v2models/app_version.go
internal/models/v2models/chart_version.go

- Easy enough to add when calling the API from GitHub Actions or whatever
- Saves me from DDOSing GitHub’s API from Beehive
- Also chart versions don’t have git info stored because they’re git-agnostic, so this is important for having the info there
- Lets us make this info editable in Beehive, which might be useful. Not like that’s hard to do in Beehive anyway
In other words, I think allowing storage of git commit messages or some other equivalent string inside Sherlock makes sense so I'm going to do it now because it is faster this way than trying to engineer a hacky temporary solution in Beehive. This took like 15 minutes.

[DDO-2382] Version description fields

---

build/server/Dockerfile

1. New service checklist says to use a blessed image
2. Denis says we should just use a distroless image directly
If we need to shell into sherlock's pod we'd need to use `kubectl debug` but in my testing the image seemed to run a very tiny bit faster? I dunno, distroless means that nothing is ever gonna flag for Trivy so 🤷‍♂️

[DDO-2396] Use distroless/static for Sherlock server

---

internal/controllers/v2controllers/changeset_test.go
internal/models/v2models/changeset.go

[Lots more context in the ticket.](https://broadworkbench.atlassian.net/browse/DDO-2395) I might eventually add logic here to assemble a correct one more often, but I kinda don't want to do that now because it's hard and regardless we'll want this better failure mode behavior.

[DDO-2395] Truncate version change logs if we weren't able to assemble a fully correct one

---

internal/handlers/v2handlers/generic_handlers.go
internal/models/v2models/chart_release_version.go
internal/models/v2models/chart_release_version_test.go

Also, make query parameter parse logs at the trace level, since debug is noisy.

[DDO-2413] Make Sherlock's Changeset#equalTo() include the new firecloudDevelopRef field

---

internal/controllers/v2controllers/changeset_procedures.go
internal/controllers/v2controllers/changeset_test.go
internal/controllers/v2controllers/model_controller.go
internal/models/v2models/changeset_event_store.go
internal/models/v2models/chart_release_version.go
internal/models/v2models/environment.go
internal/models/v2models/internal_model_store.go
internal/models/v2models/model_store.go
internal/sherlock/sherlock.go

Now that they're editable, updated_at != created_at, so we gotta order by the right thing when we care (which is only internally right now)

[DDO-2420] Fix "latest" bug introduced by App and Chart Versions now being editable

---

go.mod
go.sum
internal/sherlock/routes.go

```golang
// No origins allowed by default
router.Use(cors.New(cors.DefaultConfig()))
// Browsers shouldn't ever cache Sherlock responses
router.Use(func(c *gin.Context) {
c.Writer.Header().Set("Cache-Control", "no-store")
})
```

[DDO-2422] Sherlock HTTP Tweaks

---

db/migrations/000021_add_resource_prefix.down.sql
db/migrations/000021_add_resource_prefix.up.sql
internal/controllers/v2controllers/chart_release_test.go
internal/controllers/v2controllers/environment.go
internal/controllers/v2controllers/environment_test.go
internal/handlers/v2handlers/environment.go
internal/models/v2models/environment.go
internal/models/v2models/environment_test.go
internal/models/v2models/selector_helpers.go

A resource prefix can be given during creation, in which case it will be uniqueness checked. If you don't provide one, [Sherlock will derive one guaranteed to be unique](https://github.com/broadinstitute/sherlock/pull/83/files#diff-5c8215f59953ce46e01ca7acd0dacd8abf806c7ae0607df135592bd8501f4d1fR173). We allow it to be specified on creation mainly for the state transition where we need to import existing prefixes generated with another algorithm.
The algorithm works based on a count of all environments that have ever existed. That count is converted to a "number," where `0` would become `aaaa`, `1` would become `aaab`, etc. The count is modulo the number of possibilities, keeping in mind the restriction that it lead with a letter.
```
z    9    9    9
^^   ^^   ^^   ^^
26 * 36 * 36 * 36 = …
```

[DDO-2428] Unique Resource Prefix

---

.github/workflows/client-report-app-version.yaml

Let the app reporter callable-workflow take a lot more configuration to work with custom git context. This means that terra-helmfile's update-service can pass in a bunch of stuff about the app that it came from. It's a step.

[DDO-2486] Add a bunch more configuration to the app reporter

---

.github/workflows/client-get-environment.yaml
.github/workflows/client-set-environment-app-version.yaml

- Adds client-get-environment, which is a GHA-native mechanism to grab some info about an environment. Can easily extend it over time--just means we don't need to write curls and bash everywhere.
- Extends client-set-environment-app-version, so if you pass a GH token it'll call terra-github-workflows to sync whatever got updated. It uses client-get-environment to be smart about how it treats templates just to avoid the user gotcha.
- client-set-environment-app-version already had parity with terra-helmfile's update-service, but now it actually has full parity with fc-jenkins's gke-update-service, which is neat.

[DDO-2520] New client actions

---

.github/workflows/client-set-environment-app-version.yaml

It seems like the the `sync-release` workflow in terra-github-workflows requires a boolean input of `refresh-only` that wasn't being passed here.

DDO-2522 Fix missing input to workflow dispatch

---

.github/workflows/client-get-chart-release.yaml
.github/workflows/client-set-environment-app-version.yaml

Fix https://github.com/broadinstitute/terra-github-workflows/actions/runs/3680813391/jobs/6226816953 -- right now we need to pass the actual chart release name, so we just ask Sherlock for it. Maybe this approach is a bit heavyweight, but it's also bulletproof, so whatever.

[DDO-2520] Convert env/chart to chart release name in GHA

---

.github/workflows/client-get-chart-release.yaml
.github/workflows/client-get-environment.yaml
.github/workflows/client-refresh-environment.yaml
.github/workflows/client-report-app-version.yaml
.github/workflows/client-set-environment-app-version.yaml

Turns out that some of the internal naming gets exposed at the top level in the workflow graph that GHA helpfully shows. I'm changing some internal stuff here to make it look prettier; here's an example of what it looks like now https://github.com/DataBiosphere/terra-workspace-manager/actions/runs/3688913109 (notice the "get" and "set" nonsense)

[DDO-2530] Tweak internal GHA naming

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/v2controllers/changeset_procedures.go
internal/controllers/v2controllers/changeset_test.go
internal/handlers/v2handlers/changeset.go
internal/models/v2models/changeset_event_store.go

Supports an offset and limit which I'll have to use if I put this in Beehive because querying like this can get heavy.

[DDO-2564] Allow API users to query applied Changesets for a given Chart Release

---

html/close.html
html/html.go
internal/sherlock/routes.go

Allows frontend Javascript on other origins to initiate user IAP sessions with Sherlock without landing the user at the Swagger page or an IAP intercept.

[DDO-2581] Have Sherlock host a static self-closing page

---

internal/controllers/v2controllers/chart_release.go
internal/controllers/v2controllers/environment.go
internal/models/v2models/changeset_event_store.go

- When returning an Environment or ChartRelease, if the associated PagerdutyIntegration wasn't loaded, still include its ID in the response (since the ID is in the Environment or ChartRelease's own database row, we might have it)
- When mutating an Environment or ChartRelease, at least handle the case where someone set the PagerdutyIntegration to ""
- There's not a good way to zero out the field. For string fields, we can just store the "" in the database because "" isn't nil, so it's detected by Go as an actual value. At the database level, though, this field is a numeric ID. Not just that, it's a foreign key. We can't just set it to 0 because that's actually semantically different, and I think SQL would reject the bad association. We want to explicitly set it to nil, but because of Go's …

[DDO-2593] Fix PagerdutyIntegration handling in Environment and ChartRelease

---

internal/metrics/v2metrics/metrics.go
internal/models/v2models/metrics_updater.go

Figure I'd get this in before doing a Sherlock bump.
Means Sherlock will report how many BEEs are online versus offline. Thelma will report metrics for it applying scheduling and we can pull Kubernetes metrics for node count to actually iron out the whole system.
Deletion prevention included too to help us identify which BEEs don't have a schedule--right now, deletion-prevented ones have scheduling features hidden in Beehive.

[DDO-2669] Add environment state metrics

---

internal/controllers/v2controllers/environment.go
internal/utils/time.go
internal/utils/time_test.go

GO POINTER LOGIC STRIKES AGAIN
so you know how go structs initialize every field
and we use pointers a bunch so that we have nil in all those fields so that we don't accidentally overwrite stuff with zero values?
well the openapi library for golang doesn't bother with that. It's _smarter_, and uses a mix of pointer and non-pointer fields plus some `json:",omitempty"`. Except this doesn't work for their homebrew strfmt.DateTime type, which gets initialized to an empty time.Time{} internally but then never gets omitted from the JSON. So every time Thelma mutates an environment, it'll overwrite the schedule with zero, which is literally just wrong.
I can't control them but I can control me, so I wrote the stupidest little function ever:
```golang
func NilOrNonZeroTime(t *time.Time) …
```

[DDO-2669] Have Sherlock ignore passed zero times

---

internal/controllers/v2controllers/user_procedures.go
internal/controllers/v2controllers/user_test.go

Added a test for this very specific narrow case, that happens to be the case for a lot of real-world cases. Just meant some superfluous database writes when it was writing the same name as was already stored.

[DDO-2738] Don't update users every single time

---

.github/workflows/client-report-chart-version.yaml

creates a new workflow call action for reporting chart versions to sherlock, similar to client-report-app-version.
Differences:
- parent-chart-version is now optional, as chart publishing requires a git push, and is optional on the repo, so using the git tag log is unreliable. So instead of trying to predict and possibly getting the parent wrong, just don't set it.
- datarepo, for instance will promote `datarepo-api` or `datarepo-ui` and then `datarepo`, right now these are seperate-serial commits, but we should not depend on this behavior for correctness.
- git PR branch removed. expect that published charts are always mainline. left override in case of some wierd edge case.
- commit unchanged
- description unchanged, might end up being a trivial comment (i.e. automated chart bump), but …

add new report chart version call

---

.github/workflows/client-set-environment-app-version.yaml
.github/workflows/client-set-environment-chart-version.yaml

copies client-set-environment-app-version.yaml, but for charts, also updates some deprecation from using old workflow dispatch.
testing: will do testing later when calling from datarepo-helm

add new workflow, update other dispatches

---

internal/db/test_helpers.go

🤷 
I can't think of a good reason why we would ever want to run Sherlock tests against a database that had been set up by Cloud SQL... so this seems like an easy enough thing to add. It's not perfect but it's way hardier than doing nothing.
It doesn't panic in the normal case, and then I modified the local postgres with datagrip to add a dummy role named `cloudsqladmin`. Running tests again immediately failed with 
```
test_helpers.go:20: this database looks like it is running in Cloud SQL, refusing to proceed with test harness
```
and then a giant stacktrace with a bunch of nil pointer dereferences and various panics. Close enough 🤷

[DDO-2847] Make Sherlock panic if `cloudsqladmin` role is in the test database

---

.github/workflows/sherlock-build.yaml

It was making both `sherlock` and `server` images before, but now that https://github.com/broadinstitute/terra-helmfile/pull/4277 is merged and deployed we don't need to do that
https://ap-argocd.dsp-devops.broadinstitute.org/applications/sherlock-dsp-tools?resource=&node=argoproj.io%2FApplication%2Fap-argocd%2Fsherlock-dsp-tools%2F0 shows that the `sherlock` image is being used, not the `server` one
Super low, worst case is that something gets out of date

[DDO-2893] Remove image push double-writing

---

internal/boot/router.go

I totally forgot that these need to be exposed by Sherlock's actual router. They were being exposed by the v1 api part so I forgot that they were still necessary here.
404'ed before locally, now it returns normally
Super low, this is a bug fix just exposing existing functionality

[DDO-2896] Fix Sherlock metrics

---

sherlock/db/migrations/000043_add_started_at.down.sql
sherlock/db/migrations/000043_add_started_at.up.sql
sherlock/internal/controllers/v2controllers/ci_run.go
sherlock/internal/controllers/v2controllers/ci_run_test.go
sherlock/internal/models/v2models/ci_run.go

There's a createdAt that I was intending to use, but that actually gets set when the workflow is queued, as opposed to when it starts running (based on how GitHub sends up webhooks). Figure I'll make space to record the actual value and make a subsequent PR once this is deployed to update the cloud function.
Migration worked against my copy of the database, and I added tests
Minimal IMO

[DDO-2903] Add a startedAt field to the CiRun schema

---

.github/workflows/sherlock-lint.yaml
sherlock-webhook-proxy/README.md
sherlock-webhook-proxy/pkg/handler.go

Takes advantage of #178, just in the webhook. Also enables linting for the webhook directory.
Deployed it and its happy. (The deploy process does some checks that it starts up and stuff, so it isn't a blind deploy)
Minimal IMO

[DDO-2903] Set startedAt from webhook

---

sherlock/internal/metrics/v2metrics/metrics.go
sherlock/internal/models/v2models/ci_run.go
sherlock/internal/models/v2models/internal_model_store.go
sherlock/internal/pagerduty/metrics.go

It exposes a count of completions and a sum of seconds spent. Both can be broken down by repo, workflow file, attempt number, and outcome.
These are ephemeral Sherlock metrics, more similar to the PagerDuty request metrics (that I think I never demo-ed, but they're there) than the accelerate metrics. Rather than being calculated on startup and reported as "LastValue" they're sent as requests come in and reported as "Count" or "Sum" (thus being aggregated with existing values Thanos has stored, not replacing them).
I ran Sherlock and the webhook proxy locally. Then I ran Sherlock's [test-auth-transparency.yaml](https://github.com/broadinstitute/sherlock/blob/main/.github/workflows/test-auth-transparency.yaml) workflow three times. The middle invocation was me retrying the first.
Here's …

[DDO-2904] Expose metrics from Sherlock's CiRuns

---

sherlock/internal/metrics/v2metrics/metrics.go
sherlock/internal/models/v2models/ci_run.go
sherlock/internal/models/v2models/internal_model_store.go
sherlock/internal/pagerduty/metrics.go

This reverts commit 8666c75a448432cc2a05a5c0292c987fa55ca268 per https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1686576979386449. That commit made no changes to the database, so this should be safe to do.

Revert "[DDO-2904] Expose metrics from Sherlock's CiRuns (#180)"

---

sherlock/internal/metrics/v2metrics/metrics.go
sherlock/internal/models/v2models/metrics_updater.go

Take-two on #180.
It exposes four metrics:
- `v2_github_actions_1_hour_completion_count`
- `v2_github_actions_7_day_completion_count`
- `v2_github_actions_1_hour_total_duration`
- `v2_github_actions_7_day_total_duration`
Each has four labels associated to it:
- `gha_repo` like `broadinstitute/beehive`
- `gha_workflow_file` like `.github/workflows/build.yaml`
- `gha_outcome` like `success`
- `gha_retry` like `true` or `false`
Unlike #180, these metrics are fully-calculated by Sherlock. It exposes graphable values directly, instead of counts. This behavior is similar to how accelerate metrics work. The benefit is that Sherlock can, y'know, calculate these things _correctly_, with SQL, rather than relying on Prometheus's ability to add numbers.
I developed the SQL against a local copy of the …

[DDO-2904] Precalculated CiRun metrics

---

sherlock/internal/models/v2models/metrics_updater.go

Talking to Eno about SQL made me realize I could potentially do this all in one step. So this is one query rather than four, _and_ it reports 0 for things like "no retries in the time period" which becomes super useful for Prometheus down the line.
It's also just literally less code, no looping, and no string replacement inside SQL statements.
Metrics that aren't 0 look the same, but there's way more zeros now (verified locally)
None

[DDO-2904] Precalculated metrics for CiRun, but better

---

.github/workflows/client-get-chart-release.yaml
.github/workflows/client-get-environment.yaml
.github/workflows/client-refresh-environment.yaml
.github/workflows/client-report-app-version.yaml
.github/workflows/client-report-chart-version.yaml
.github/workflows/client-report-workflow-related-resources.yaml
.github/workflows/client-set-environment-app-version.yaml
.github/workflows/client-set-environment-chart-version.yaml

This PR does three things, all related to the "client" workflows that Sherlock's repo offers.
1. Remove calls to sherlock-dev (hundreds lines of complexity and confusing error codes for no reason)
2. Add a workflow that hits [this endpoint](https://sherlock.dsp-devops.broadinstitute.org/swagger/index.html#/CiRuns/put_api_v2_ci_runs__selector_) to tell Sherlock "this action affected X" (this is the same endpoint that webhooks hit, and the selectors line up, so this is editing the same CiRun that the webhook created. There's no race condition here, it's okay if one or the other gets delayed -- they're upsert operations.)
3. Add said workflow to the other client workflows. So if you report a new app version, automatically your GHA will be flagged as being related to that app version. If you …

[DDO-2914] Reusable workflow for reporting related resources

---

sherlock/config/default_config.yaml
sherlock/internal/boot/application.go
sherlock/internal/boot/application_test.go
sherlock/internal/boot/liveness/server.go
sherlock/internal/boot/liveness/server_test.go

It now uses the sql package's Ping method to check that the database connection is healthy, on a configurable interval.
It doesn't try to preemptively exit, it just makes the liveness endpoint return differently so that Kubernetes handles it.
The lifecycle technically looks like this:
1. `Server.Start()`
2. `Server.MakeAlwaysReturnOK()`
3. `Server.Stop()`
That second step is a bit of a technicality. When we shut down Sherlock, we don't want the liveness probe evaluating the health of the database connection pool as we drain it--we want it to still consider Sherlock alive while it is shutting down, so Kubernetes doesn't get trigger-happy. We call `Server.MakeAlwaysReturnOK()` right before initiating the database disconnect during shutdown to get the behavior we want.
> **Note**
> In …

[DDO-2976] Improve Sherlock's liveness endpoint

---

sherlock/go.mod
sherlock/go.sum
sherlock/internal/api/sherlock/ci_identifiers_v3_get.go
sherlock/internal/api/sherlock/ci_identifiers_v3_list.go
sherlock/internal/api/sherlock/ci_runs_v3_get.go
sherlock/internal/api/sherlock/ci_runs_v3_list.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/api/sherlock/handler_test.go
sherlock/internal/errors/abort.go
sherlock/internal/errors/abort_test.go

The old CiRun PUT endpoint had this gimmick where when you report that a GHA relates to a Changeset, it also records that the GHA relates to any new app or chart versions that Changeset deployed.
That works fine, but it would get spammy if we use it more, because BEE deployments would then show up when you look at an app or chart version's CiRuns.
So the v3 one I added has that behavior behind a flag in the request. It's disabled by default. No more spam.
Except... what we really want is "enable this for deployments to static environments, disable it otherwise." We _want_ deployments to dev/alpha/staging/prod to show up if you look at the CiRuns for an app version.
Rather than requiring clients to figure that out and control the flag, this PR turns the boolean flag into an enum that …

[DDO-2981] Improve app/chart version CI reporting based on changesets

---

.github/workflows/sherlock-dependency-review.yml

"Dependency Review" is a first-party workflow offered directly by GitHub at https://github.com/broadinstitute/sherlock/actions/new. It's backed by GitHub's API, I tried it and it works even though we're in a monorepo. Seems like an easy win to add, I didn't touch the workflow file.

[DDO-2982] Block introduction of vulnerable packages into Sherlock's codebase

---

sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/boot/application.go
sherlock/internal/boot/application_test.go

An improved bit of resilience based on my idea here https://broadinstitute.slack.com/archives/C029LTN5L80/p1690468925684809?thread_ts=1690468008.475729&cid=C029LTN5L80
An application-level mutex lock is actually a bit easier for us to work with than trying to repeatedly query the actual database lock table, and it solves the issue here equally well.
Also fixing a flakey test here, just borrowing my fix from #220 because that PR won't be ready for a bit.
I think this case is basically impossible to hit. But I wrote a test that hits it anyway.
None

[DDO-2991] Block shutdown during migrations

---

sherlock/internal/db/connect.go
sherlock/internal/deprecated_db/test_helpers.go

Run it during db.Connect() rather than db.Configure(). Noticed this possible improvement while doing #221.
These codepaths are already tested.
None

[DDO-2992] Run the "panic if cloud SQL" check earlier

---

sherlock/docs/docs.go
sherlock/docs/swagger.json
sherlock/docs/swagger.yaml
sherlock/internal/api/sherlock/ci_identifiers_v3_list.go
sherlock/internal/api/sherlock/ci_runs_v3_list.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/api/sherlock/users_v3.go
sherlock/internal/api/sherlock/users_v3_get.go
sherlock/internal/api/sherlock/users_v3_get_test.go
sherlock/internal/api/sherlock/users_v3_list.go
sherlock/internal/api/sherlock/users_v3_list_test.go
sherlock/internal/api/sherlock/users_v3_upsert.go
sherlock/internal/api/sherlock/users_v3_upsert_test.go
sherlock/internal/authentication/db_middleware.go
sherlock/internal/authentication/user_middleware.go

Adds refactored v3 user endpoints that expose suitability. This is safe because the entire API is only accessible from internal users; there's not information leakage since the entire audience is allowed to know the info we're exposing.
The PUT endpoint now does the GitHub account linking instead of having a separate endpoint for it. It's a bit weird because we basically _need_ to proxy the GitHub API in order for the operation to be secure (we need to call the GitHub API with the user's token), but that's not new, that's existing behavior that I'm just replicating into the refactored world.
An important note here is that the model-level user stuff was already added in #202, I'm just going to the effort of exposing it in the API now.
There's tests for everything I can test offline. The …

[DDO-2989] v3 Users endpoints that expose suitability

---

.github/workflows/client-report-workflow-related-resources.yaml
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go

Sometimes maybe we'd prefer Sherlock to swallow errors, for example if someone says "this workflow relates to my-random-chart" but that chart doesn't yet exist in Sherlock. This new optional API field does exactly that.
Code coverage goes down because Go error handling is a LoC factory but I did test both sides of this behavior.
Extremely low IMO, new optional field.

[DDO-3006] Let CiRun upsert ignore bad selectors

---

foundation.yaml

I'm experimenting with [backstage](https://backstage.spotify.com/) for Foundation purposes and need some real services to be able to try features out on my dev instance so I'm using sherlock and beehive. This metadata file is what enables services to be registered in the foundation service catalog
This is a 0 zero risk PR, functional change just adds a project metadata file for foundation to consume.

Experimenting with Software Catalog for Foundation - Add foundation.yaml

---

sherlock/internal/models/app_version.go
sherlock/internal/models/chart_release.go
sherlock/internal/models/chart_release_version.go
sherlock/internal/models/chart_version.go
sherlock/internal/models/cluster.go
sherlock/internal/models/environment.go
sherlock/internal/models/pagerduty_integration.go

To support me adding post-deploy hook stuff to Sherlock's database, I want to be able to reference these data types directly in the new models. Rather than going the effort of adding refactored APIs for all these types as a blocker, this PR just adds the structs themselves. It's suitable for reading but not for writes--luckily,reading is all I need.
Not tested but not used either, this is dead code as written. These are just struct definitions that I just copied, I'm not going to the effort of unit testing that right now.
None, I'm adding some dead code.

[DDO-3019] Add more refactored read-only models

---

makefile
sherlock/config/test_config.yaml
sherlock/internal/db/connect_test.go

`make local-up` and `make pg-up` both use :5432 for the Postgres. That makes it possible to accidentally run tests against the (presumably data-filled) Postgres for `make local-up`.
This PR makes tests and the test Postgres use :5431. Seems like an easy tweak to improve the DX and make it harder to accidentally wipe the real local database. Also means you can have both running at once.

[DDO-3020] Use a different port for the test Postgres

---

dev/local-with-pg.yaml
sherlock/internal/config/config.go

Found out that Koanf is case-sensitive and the example "how to parse env" code they give is wholly unable to handle camel-cased keys... like `slack.appToken`. Great.
This PR now parses environment variables twice: once where it lowercases (just the existing behavior) and once where it doesn't (so that `SHERLOCK_slack_appToken`, while ugly, will work).
I toyed with the docker-compose config, mixing and matching the environment variable formats to check that Sherlock was reading both simultaneously.
If this doesn't work, Sherlock won't start and we'll sit at one replica -- no big deal.

[DDO-3036] Let Sherlock use case-sensitive env vars

---

sherlock/internal/authentication/user_middleware.go
sherlock/internal/errors/abort.go
sherlock/internal/errors/errors.go

Middleware wasn't using the right helper so errors weren't getting stored in the Gin context in a way that the Slack error reporting could read. This PR fixes that and makes the "shouldn't be called externally" helper private so that we'll avoid this oopsie in the future.
Uses the same helper tested everywhere else (even though this is an IAP function that we can't directly test, we're removing a code path here)
None

[DDO-3038] Make Sherlock middleware put errors in Gin ctx

---

foundation.yaml

Accidentally duplicated a resource name, apparently backstage silently ignores this.

Fix cloudfunction Name: oops

---

sherlock/internal/boot/router.go

We don't want a host when Sherlock runs the Swagger page itself -- we want the page to loopback to whatever is hosting it -- but when read statically by something like Backstage, this helps the spec be properly understood by the Swagger javascript bundle.
`make generate-docs` fills the host into the generated files, but `make local-up` makes it look exactly as before, _where it still connects to localhost:8080_
None

[DDO-3034] Make Swagger spec have a host when read statically

---

sherlock/config/default_config.yaml
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_create.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_delete.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit.go
sherlock/internal/slack/link_helper.go
sherlock/internal/slack/link_helper_test.go
sherlock/internal/slack/report_error.go
sherlock/internal/slack/report_error_test.go
sherlock/internal/slack/send_message.go
sherlock/internal/slack/send_message_test.go

Extract out the core message sending from slack.ReportError, giving us a slack.SendMessage function too.
I made it so that creating/editing/deleting a SlackDeployHook will fire off a Slack message using it--not the most in-depth Slack message because I didn't want to spend a lot of time here, just something best-effort felt like it'd be enough.
I also made slack.ReportError accept a list of errors so you can dump multiple into it and it'll figure it out.
Tests for all this stuff. Woohoo.
Super low / none IMO

[DDO-3045] Make Slack message sending more general

---

sherlock/config/default_config.yaml
sherlock/internal/api/sherlock/ci_runs_v3.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/boot/application.go
sherlock/internal/deployhooks/ci_run_is_deploy.go
sherlock/internal/deployhooks/ci_run_is_deploy_test.go
sherlock/internal/deployhooks/deployhooks_test.go
sherlock/internal/deployhooks/dispatch_ci_run.go
sherlock/internal/deployhooks/dispatch_ci_run_test.go
sherlock/internal/deployhooks/dispatch_github_actions_deploy_hook.go
sherlock/internal/deployhooks/dispatch_slack_deploy_hook.go
sherlock/internal/deployhooks/dispatch_slack_deploy_hook_test.go

It does the deploy hook thing (just for Slack, but still).
"What is a deploy" is [defined in config](https://github.com/broadinstitute/sherlock/pull/255/files#diff-4d384cde637e16a25a2c337aa142a42be5b727ab3b5d5f52db3d864844e392a7). Everything else is defined via the API.
If there were changesets reported by the deploy, the Slack message will link out to the Beehive page to view them. Easier than writing a ton of code to try to summarize all that again in Slack. Might do that at some point, but the current Jenkins notifications don't do that, so we're already past parity.
Lots of tests -- not quite end to end (hard to set up mocks from outside the package, that kinda thing) but complete enough that I'm confident here. Enough that project coverage goes up, even with the stuff I'm introducing …

[DDO-3046] Slack Deploy Hooks

---

sherlock/internal/db/connect.go

From https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL, how to disable PGX prepared statements cache, which appeared to cause the errors we saw in https://broadinstitute.slack.com/archives/C011NQS8Q2Z/p1692298158181069
If this didn't work the entire testing thing would fall over
Super low I think! Sherlock isn't really high-volume so I don't think performance will degrade by that much

[DDO-3048] Disable prepared statements cache

---

.github/dependabot.yaml
makefile
sherlock-webhook-proxy/README.md
sherlock-webhook-proxy/go.mod
sherlock-webhook-proxy/pkg/handler.go

A consequence of our shiny new Beehive GitHub app needing to span multiple orgs is that it needs to be a public app. That means anyone can install it. That's wouldn't really be a problem -- if random people want to give us read/write on their repo, not really our problem -- except that it'll loop us in to webhook events coming from their installation.
Solution is to filter out unknown orgs. Then the data never reaches Sherlock, and we're in the same security model as before, where this is a public cloud function that'll happily eat spurious requests.
In other words, this change prevents Sherlock from ever being affected if some random person figures out how to install our GitHub Apps.
While I was at it, I touched up the code a little bit and enabled Dependabot.
I copied/pasted the updated …

[DDO-3053] Harden Sherlock's webhook proxy

---

makefile
sherlock-webhook-proxy/pkg/handler.go

In hindsight, I guess it makes sense that `gcloud` would be unhappy with comma-separated stuff, even in quotes, because it isn't like it gets to see the fact that it's in quotes.
Whatever, now it's space-separated.

[DDO-3053] Fix proxy cloud function deployment

---

sherlock/internal/deprecated_controllers/v2controllers/changeset_procedures.go
sherlock/internal/deprecated_controllers/v2controllers/changeset_test.go
sherlock/internal/deprecated_handlers/v2handlers/changeset.go
sherlock/internal/deprecated_models/v2models/changeset.go
sherlock/internal/deprecated_models/v2models/changeset_store.go

It's `/api/v2/procedures/changesets/query-applied-for-version/{version-type}/{chart}/{version}`, you use it like `/api/v2/procedures/changesets/query-applied-for-version/app/sam/v0.0.102` and it returns a list of what changesets deployed that version, in timeline order (first is the latest applied).
When possible, it will handle scenarios where the specified version was an intermediary version, i.e. you care about version 2 but prod when from 1 to 3 directly. This endpoint will include that 1 to 3 changeset if you ask for 2.
If you ask for a version that was never recorded in Sherlock, it will still do a best effort search (but it obviously can't do the intermediary-version detection then).
Manually tested against my clone of prod. It would take me another day to actually create a …

[DDO-3060] API to create a timeline of when/where a version was deployed

---

sherlock/internal/deployhooks/dispatch_github_actions_deploy_hook.go
sherlock/internal/deployhooks/dispatch_github_actions_deploy_hook_test.go
sherlock/internal/github/dispatch_workflow.go
sherlock/internal/github/dispatch_workflow_test.go

1. GitHub's API isn't consistent with how it treats workflow file paths. It gives us the full file path in some APIs, but this one fails if you don't pass just the filename in. This PR make our wrapper just handle that so we don't have to worry about it.
2. Turns out HEAD isn't recognized by this endpoint. Not a big deal, our API already requires that a specific default ref be passed in, but I'll remove HEAD as an internal failsafe.
Updated our tests, full coverage over changes
None

[DDO-3072] GH deploy hook fixes

---

sherlock/internal/api/sherlock/ci_runs_procedures_v3_github_info_list.go

I messed up this comment, so the Swagger type that gets generated is incorrect.

[DDO-3075] Fix Swagger

---

sherlock/db/migrations/000051_rename_dispatched_at.down.sql
sherlock/db/migrations/000051_rename_dispatched_at.up.sql
sherlock/internal/api/sherlock/ci_runs_v3.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/models/ci_run.go
sherlock/internal/models/ci_run_test.go

terminationHooksDispatchedAt is a better name for the field because of some of the changes I think we'll be making in the future. This isn't a fancy zero-downtime rename because frankly the prepared statement cache will cause issues anyway, so might as well just do it all at once.
Tests work and I ran this against my local copy of prod to check that the migration works and doesn't take a while
Might drop an automated CiRun request or two if we get unlucky. I think that's okay -- the absolute worst case scenario is that we don't send a slack notification for a deployment. Sherlock will DM us the errors so we'll know what needs cleanup.
That said, I'm still going to deploy this off-hours. Just easier for me to spend 5 seconds running a command tonight than make like 7 PR-deploy cycles to do …

[DDO-3100] Rename deployHooksDispatchedAt

---

sherlock/config/default_config.yaml
sherlock/internal/db/connect.go

As documented on https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL, PGX enables a prepared statement cache by default. Enabling Gorm's config for "PreferSimpleProtocol" disables it.
This PR adds this to the config file, so that we can toggle this option from argo or something without needing to release a new Sherlock version
This line covered by connected DB tests already
Maintains the current default behavior (prepared statement cache true -> prefer simple protocol false)

[DDO-3108] Prepared statement cache toggle

---

.github/workflows/client-refresh-environment.yaml
.github/workflows/client-report-app-version.yaml
.github/workflows/client-report-chart-version.yaml
.github/workflows/client-set-environment-app-version.yaml
.github/workflows/client-set-environment-chart-version.yaml
.github/workflows/test-auth-transparency.yaml

Go from client-report-workflow-relates-resource.yaml to client-report-workflow.yaml. Works the same for this stuff but prefixes the old inputs with `relates-to-`.
I briefly modified test-auth-transprancy.yaml to use the new workflow and send a slack notification, checking as best I can that this doesn't blow everything up.
GHA are really hard to test. I've checked this over as best I can -- hopefully you can see the uniformity in the diff. GitHub does now check the syntax of GHA pushed to branches, you'll see errors in the actions tab if they're invalid. So if there are errors they should be logical instead of workflow-crashing.

[DDO-3101] Cut over GHA to use the new client-report-workflow

---

sherlock/db/migrations/000053_changeset_user.down.sql
sherlock/db/migrations/000053_changeset_user.up.sql
sherlock/internal/deprecated_controllers/v2controllers/changeset.go
sherlock/internal/deprecated_controllers/v2controllers/changeset_test.go
sherlock/internal/deprecated_models/v2models/changeset.go
sherlock/internal/models/changeset.go

Remember users who plan and apply changesets. Adds `plannedBy`, `plannedByInfo`, `appliedBy`, and `appliedByInfo` to the changeset spec. All are technically nullable, but plannedBy is filled upon creation going forward.
Wired this in to the tests. Codecov gets confused with the generics, it's coverage stats are wrong here I believe.
Just additive, and I took care to avoid scenarios where Gorm might try to recursively update (I only assign IDs, never to the full field).

[DDO-3113] Remember changeset planners and appliers

---

.github/workflows/client-report-app-version.yaml

Rather than assuming one git command will be able to figure out what branch a GHA is running on, we now have two layers.
It used to just run `git rev-parse --abbrev-ref HEAD`, but that returns HEAD if the GHA is running directly on a tag.
The first runs `git branch --show-current`. If we're on a branch, that returns it. Nice and easy.
The second runs if we didn't find anything with that. It runs `git branch --format='%(refname:short)' --list --contains $(git rev-parse HEAD) | awk '{$1=$1};NF' | grep -v -F " " | head -n 1`, which lists branches containing the current checked-out commit, filters consecutive spaces and blank lines, filters out "blah detached at blah", and grabs the first line. That comes up with a reasonable branch name in many cases, which is better than HEAD (which is …

[DDO-3124] Improve app version reporting from detached tags or commits

---

.github/workflows/client-report-workflow.yaml
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go

Now, if the workflow is marked as relating to a chart release (or environment), the message will no longer look like this:
> terra-java-project-template's build-and-test workflow: [success](https://github.com/DataBiosphere/terra-java-project-template/actions/runs/6125147705/attempts/1)
It'll look like this (hypothetically, fake example)
> terra-java-project-template's build-and-test workflow against [javatemplate-dev](example.com): [success](https://github.com/DataBiosphere/terra-java-project-template/actions/runs/6125147705/attempts/1)
Not amazing but it's a lil better. Tests included.

[DDO-3126] Improve Slack notifications

---

sherlock/internal/deprecated_models/v2models/changeset.go

I want to include the index in the Slack message because there's a chance this isn't working as well as I want (the index is in the other error message that's getting dumped to Slack)

[DDO-3127] Improve changeset logging

---

sherlock/config/default_config.yaml
sherlock/db/migrations/000054_add_helmfile_ref_enabled.down.sql
sherlock/db/migrations/000054_add_helmfile_ref_enabled.up.sql
sherlock/internal/api/sherlock/ci_identifiers_v3_get_test.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/api/sherlock/deploy_hook_trigger_configs_v3_test.go
sherlock/internal/deployhooks/dispatch_ci_run_test.go
sherlock/internal/deployhooks/dispatch_github_actions_deploy_hook_test.go
sherlock/internal/deployhooks/dispatch_slack_deploy_hook_test.go
sherlock/internal/deprecated_controllers/v2controllers/changeset.go
sherlock/internal/deprecated_controllers/v2controllers/changeset_procedures.go
sherlock/internal/deprecated_controllers/v2controllers/changeset_test.go
sherlock/internal/deprecated_controllers/v2controllers/chart_release.go
sherlock/internal/deprecated_models/v2models/chart_release_version.go
sherlock/internal/deprecated_models/v2models/chart_release_version_test.go
sherlock/internal/deprecated_models/v2models/environment.go
sherlock/internal/models/chart_release_version.go
sherlock/internal/models/deploy_hook_trigger_config_test.go
sherlock/internal/models/github_actions_deploy_hook_test.go
sherlock/internal/models/slack_deploy_hook_test.go

This PR adds a new boolean field, `HelmfileRefEnabled`, to ChartRelease, that defaults to false. It quacks like `HelmfileRef`. In other words, whenever or wherever `HelmfileRef` is copied or promoted from one chart release to another, the `HelmfileRefEnabled` field is as well.
This PR also updates Sherlock's Changeset logic so that when a new Changeset is planned, if `HelmfileRefEnabled` is:
* `true`: `HelmfileRef` will not be touched, because someone intentionally set the chart release to a custom ref
* `false`: `HelmfileRef` will be set to `HEAD`
This PR also adds a new config flag, `model.changesets.helmfileRefDefaultToChartReleaseTags`, currently set to `false`. When flipped, to true, the promotion described above will set `HelmfileRef` to `charts/<name>-<version>` instead of `HEAD`. …

[DDO-3141] Add new `HelmfileRefEnabled` field

---

sherlock/config/default_config.yaml
sherlock/internal/deprecated_controllers/v2controllers/changeset_test.go
sherlock/internal/deprecated_models/v2models/chart_release_version.go

Enable the chart release tag promotion feature, which was introduced in https://github.com/broadinstitute/sherlock/pull/295
The linter failures seem to be known and happening on mainline.

[DDO-3161] Enable chart release tag promotion

---

sherlock/config/default_config.yaml

Per [Jack Warren's suggestion](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1696359038252119?thread_ts=1695817323.661329&cid=CQ6SL4N5T), update Sherlock to also trigger deploy hooks when sync-environment is run.

[DDO-3194] Also trigger deploy hooks when sync-environment is run

---

sherlock/db/migrations/000057_cluster_v3.down.sql
sherlock/db/migrations/000057_cluster_v3.up.sql
sherlock/internal/api/sherlock/app_version_v3.go
sherlock/internal/api/sherlock/charts_v3_list.go
sherlock/internal/api/sherlock/clusters_v3.go
sherlock/internal/api/sherlock/clusters_v3_create.go
sherlock/internal/api/sherlock/clusters_v3_create_test.go
sherlock/internal/api/sherlock/clusters_v3_delete.go
sherlock/internal/api/sherlock/clusters_v3_delete_test.go
sherlock/internal/api/sherlock/clusters_v3_edit.go
sherlock/internal/api/sherlock/clusters_v3_edit_test.go
sherlock/internal/api/sherlock/clusters_v3_get.go
sherlock/internal/api/sherlock/clusters_v3_get_test.go
sherlock/internal/api/sherlock/clusters_v3_list.go
sherlock/internal/api/sherlock/clusters_v3_list_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/authentication/test_users/test_suite_helper.go
sherlock/internal/deprecated_controllers/v2controllers/cluster_test.go
sherlock/internal/errors/errors.go
sherlock/internal/models/cluster.go
sherlock/internal/models/cluster_test.go
sherlock/internal/models/deploy_hook_trigger_config_test.go
sherlock/internal/models/github_actions_deploy_hook_test.go
sherlock/internal/models/slack_deploy_hook_test.go
sherlock/internal/models/user.go

It's a bird, it's a plane, it's the same API you know and love for _clusters_ except it doesn't use generics!
The only other change here is that I made the charts list endpoint not cap at 100 because I realized that was going to either absolutely bite us in the ass or never matter.
Lots of tests. Test coverage number go up.
Existing tests all pass too! Super low risk.

[DDO-3184] Cluster v3

---

sherlock/internal/deployhooks/dispatch_ci_run.go
sherlock/internal/deployhooks/dispatch_ci_run_test.go

It was ignoring the status when deciding when to run a deploy hook before.
Added a big ol' test that checks it now.
Very low

[DDO-3195] Properly handle the outcome of CiRuns for conditionally triggering deploy hooks

---

sherlock/internal/deployhooks/dispatch_slack_deploy_hook.go

It isn't everything that Gary asked for -- I think he wants some sort of structured table in the Slack message? -- but this is what's actually feasible at the moment. Function from https://pkg.go.dev/sort#Strings
It's, uh, not, because I'm just calling a standard library function to sort a list. I believe we'll rework this before long so I'm not going to go out of my way to make a big test here. Can't be worse than the unsorted it currently is.
Very low.

[DDO-3175] Sort chart release names in Slack message

---

sherlock/internal/api/sherlock/app_version_procedures_v3_changelog.go
sherlock/internal/api/sherlock/app_version_procedures_v3_changelog_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/models/app_version.go
sherlock/internal/models/app_version_test.go

Adds `/api/app-versions/procedures/v3/changelog`. It runs with hundreds fewer database roundtrips than `/api/v2/procedures/app-versions/children-path-to-parent` but runs the same algorithm, it just does so within the database using `WITH RECURSIVE`. We discussed this and its tradeoffs [here](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1696536340273929).
Added tests, enough that I actually found some edge cases in the old endpoint's behavior. Rather than making breaking changes there I'll just have this endpoint handle them.
Read-only endpoint, very low.

[DDO-3204] Changelog capability for v3 app versions

---

sherlock/db/migrations/000059_version_user.down.sql
sherlock/db/migrations/000059_version_user.up.sql
sherlock/internal/api/sherlock/app_version_procedures_v3_changelog_test.go
sherlock/internal/api/sherlock/app_version_v3.go
sherlock/internal/api/sherlock/app_version_v3_edit_test.go
sherlock/internal/api/sherlock/app_version_v3_get_test.go
sherlock/internal/api/sherlock/app_version_v3_list_test.go
sherlock/internal/api/sherlock/app_version_v3_upsert_test.go
sherlock/internal/api/sherlock/chart_version_procedures_v3_changelog_test.go
sherlock/internal/api/sherlock/chart_version_v3.go
sherlock/internal/api/sherlock/chart_version_v3_edit_test.go
sherlock/internal/api/sherlock/chart_version_v3_get_test.go
sherlock/internal/api/sherlock/chart_version_v3_list_test.go
sherlock/internal/api/sherlock/chart_version_v3_upsert_test.go
sherlock/internal/models/app_version.go
sherlock/internal/models/app_version_test.go
sherlock/internal/models/chart_version.go
sherlock/internal/models/chart_version_test.go

As @katiewelch rolls out #321 and #306, we'll begin ingesting version authorship.
This will be helpful for making deploy notifications that can @ the specific folks who authored versions in the deployment.
Full coverage (including different creation mechanisms, ensuring that the pre-create hooks work)
Very low. Will need to disable the prepared statement cache before deployment so the database migration will run smoothly.

[DDO-3208] Record authors upon v3 version creation

---

sherlock/internal/api/api_test.go
sherlock/internal/api/sherlock/app_version_v3_upsert.go
sherlock/internal/api/sherlock/chart_version_v3_upsert.go

The v3 upsert endpoints work properly but the comments were indicating the endpoints were at `/api/appVersions/v3` and `/api/chartVersions/v3` instead of `/api/app-versions/v3` and `/api/chart-versions/v3`.
This means that the client libraries were getting a gin fallback 404, instead of an API-level 404 like the client libraries are built to handle. [This is why Thelma was complaining about not being able to parse the error response](https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1697048156679049?thread_ts=1697047954.711599&cid=CQ6SL4N5T) (it wasn't json that was coming back from gin).
I added a unit test to scan Sherlock's own source code files for declarations for API paths with capitalized letters in them. We can improve the regex over time if we need but it should help avoid …

[DDO-3215] Fix v3 version upsert paths

---

sherlock/config/default_config.yaml
sherlock/internal/boot/middleware/logger.go
sherlock/internal/boot/router.go
sherlock/internal/config/config.go
sherlock/internal/metrics/metrics.go
sherlock/internal/pagerduty/metrics.go

Adds metrics for response latency/count, by Gin's matched route.
Also touches up logging. Normal internal log messages are staying the same, but the Gin ones now take full advantage of Zerolog's JSON fields. Things like the status code, client IP, latency, etc are no longer logged in just a big string, they're logged as fields with Zerolog.
This makes the Gin logging slightly worse locally, but _way, way_ better through GCP. It's a balancing act and I think the Gin logs are primarily useful through GCP anyway, so I think it's okay. This also helps avoid logging things to console that we only need on GCP, like the client IP.
Before:
After: 
Screenshots above; visited /metrics to validate that part.
Very low, no functionality changing, just logs

[DDO-3268] Improve logging/metrics for Gin responses

---

sherlock/internal/boot/middleware/logger.go

Okay so I went a bit too far on the JSON-ifying, and now the GCP logs are kinda unreadable when you first open the page.
This tiny change just adds the most useful fields back to the message to improve readability in GCP.
I trigger this locally, here's a sample message content:
> `GIN  | 200 |      361.667µs |                                        unevaluated | GET     /swagger/index.html`
Very low

[DDO-3268] Bring back a bit of the old logging

---

sherlock/internal/api/sherlock/chart_version_v3_edit.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_test_run.go
sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_test_run_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_test_run.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_test_run_test.go
sherlock/internal/models/user.go
sherlock/internal/models/user_test.go
sherlock/internal/slack/send_message.go
sherlock/internal/slack/send_message_test.go

Adds endpoints to manually trigger deploy hooks. This is really just intended for test purposes, though I recognize that it could be misused. The endpoints require a minimal JSON body as protection against CSRF.
Mocked both Slack and GitHub to do this. Took quite a bit longer than writing the actual API endpoints, might not've bothered if I'd known it was going to take that long. Whatever, done now.
Extremely low

[DDO-3289] Deploy Hook test mechanism

---

sherlock/internal/slack/send_message.go

All the mocks in the world don't help if you're explicitly telling the Slack library to escape the all-important `<` and `>` characters. Whatever.
Well I dove into the library code to see that it was explicitly escaping "<" and ">". I don't know, I think trying to write tests around the library's outward HTTP behavior is more brittle than it is worth.
Very low.

[DDO-3290] Stop escaping text sent to Slack's API

---

sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_test_run.go
sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_test_run_test.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_test_run.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_test_run_test.go

```diff
-		errors.AbortRequest(ctx, err)
+		errors.AbortRequest(ctx, fmt.Errorf("error between Sherlock and GitHub: %w", err))
```
This case is fully covered by tests, updated them
None

[DDO-3289] Improve error text in deploy hook test routes

---

sherlock/config/default_config.yaml
sherlock/internal/db/connect.go
sherlock/internal/hooks/dispatch.go
sherlock/internal/hooks/dispatch_test.go
sherlock/internal/models/ci_run.go
sherlock/internal/models/ci_run_test.go
sherlock/internal/models/test_data.go

- Removes parallelism from deploy hook dispatching because it was causing test-only failures, see https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1701185908549649. Note that this entire process will always run asynchronous to the request in release mode, so it running sequentially isn't a big deal.
- Properly treats variables initialized with `range` as unsafe for reference in callbacks, see https://github.com/broadinstitute/sherlock/compare/DDO-3325-fix-hooks?expand=1#diff-72f437d900a508a1a0357ad8a1115546d77593ad763bb809e92f6fcdb50b6677R64. This was causing any CiRuns with multiple channels configured to send multiple notifications to just one of those channels, because the `channel` variable was getting reassigned.
- Return errors from the function that calculates completion text …

[DDO-3325] Remove hooks parallelism and fix callback variable reuse

---

sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/authentication/gha_oidc/parse_header.go
sherlock/internal/boot/middleware/logger.go
sherlock/internal/boot/middleware/logger_test.go
sherlock/internal/boot/router.go
sherlock/internal/hooks/dispatch.go
sherlock/internal/slack/report_error.go
sherlock/internal/slack/report_error_test.go

Right now the errors are just dumped without context. This PR merges the error reporting middleware with the request-aware logging middleware so we can include request info in the error report without creating an import cycle.
Added mocked testing for the logger middleware to validate that it indeed sends Slack messages how we'd want
Very low

[DDO-3381] Improve error reporting to Slack

---

sherlock/internal/deprecated_models/v2models/changeset.go

It's possible for chartRelease.AppVersion to be nil if the chartRelease doesn't correlate to an entry in the app version table -- for instance, [if a hotfixed version is being released](https://broadinstitute.slack.com/archives/C6DTFUCDD/p1702505132671549).
That means it isn't safe for this code to blindly use chartRelease.AppVersion.AppVersion. This was blocking promotions.

[DDO-3384] Avoid nil pointer dereferences in Pact Broker code

---

sherlock/internal/slack/deployment_notification.go

Go's type system isn't wonderful and that's sorta reflected in this library, which seems to do some plainly not allowed things if you ask it to

[DDO-3400] Wrap deployment notification blocks with sections

---

sherlock/internal/api/sherlock/app_version_v3_edit.go
sherlock/internal/api/sherlock/chart_version_v3_edit.go
sherlock/internal/api/sherlock/charts_v3_edit.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/clusters_v3_edit.go
sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_edit.go
sherlock/internal/api/sherlock/github_actions_deploy_hooks_v3_edit_test.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit_test.go

Gorm seems to be operating on data it shouldn't (data not referenced in the inputs it is being given). This is causing chart releases to be duplicated when saving deploy hooks. There's more data in the ticket but here we've got tests reproducing the problem, a fix for the problem, and a roll out of the fix to other semantically similar spots in Sherlock.
Failing test was added and then made to pass
Low. Can't be worse than how it is currently lol

[DDO-3402] Address spurious duplicates when saving deploy hooks

---

sherlock/internal/api/sherlock/ci_identifiers_v3_get.go
sherlock/internal/api/sherlock/ci_identifiers_v3_get_test.go
sherlock/internal/models/test_data.go

It's technically valid for a CiRun to not have a status or startedAt field, but we _usually_ don't want to see those CiRuns in the API. This PR makes the /api/ci-identifiers/v3/{selector} [get] endpoint not return them by default. This is a breaking change technically but it's breaking in the way we want, so I'm judging it worthy of just a minor version bump and no fanfare.
Added test data and a test for both sides of the flag and the default
Very low

[DDO-3403] Filter out stub CiRuns by default #minor

---

sherlock/db/migrations/000070_remove_slack_beta_flag.down.sql
sherlock/db/migrations/000070_remove_slack_beta_flag.up.sql

Now that #428 is deployed, this flag can be removed
Tests run fine without the column present in the database
Very low

[DDO-3400] Remove Slack beta flag from database

---

.github/workflows/sherlock-api-diff.yaml

By not specifying it, we'll use the automatic "merge commit" that GHA makes for pull_request workflows. This will avoid spurious "the API will remove the following endpoints!" in PRs that need their branch updated
It works fine in this action, see below
Very very low

[DDO-3422] Handle base ref better for the API diff action

---

sherlock/internal/hooks/slack_deploy_hook.go

Make https://broadinstitute.slack.com/archives/C6DTFUCDD/p1705549686258619 better by making it say "(No changes listed)" if there's no changes listed
This is covered by existing tests (we test that we can send arbitrary text in the EntryLines) and the Slack validator says the message JSON is valid
Very low

[DDO-3424] Handle the case where there are no changes

---

.github/workflows/client-report-workflow.yaml
sherlock/db/migrations/000072_add_ci_run_notification_icon.down.sql
sherlock/db/migrations/000072_add_ci_run_notification_icon.up.sql
sherlock/internal/api/sherlock/ci_runs_v3.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_create.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_delete.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_edit.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_test_run.go
sherlock/internal/deprecated_models/v2models/changeset.go
sherlock/internal/hooks/dispatch.go
sherlock/internal/hooks/dispatch_test.go
sherlock/internal/hooks/dispatcher.go
sherlock/internal/hooks/hooks_mocks/mock_mockable_dispatcher.go
sherlock/internal/hooks/slack_completion_notification.go
sherlock/internal/hooks/slack_completion_notification_test.go
sherlock/internal/models/ci_run.go
sherlock/internal/slack/report_error.go
sherlock/internal/slack/send_message.go
sherlock/internal/slack/send_message_test.go

Does what it sends on the tin. Handles colons shortcodes and URLs. I just added a parameter to the SendMessage function rather than trying to come up with something fancier
Added to all mocks and tests
Very low

[DDO-3436] Allow customizing the Slack icon for CiRun completion messages

---

sherlock/internal/hooks/dispatch.go
sherlock/internal/hooks/dispatch_test.go
sherlock/internal/models/github_actions_deploy_hook.go
sherlock/internal/models/github_actions_deploy_hook_test.go
sherlock/internal/models/slack_deploy_hook.go
sherlock/internal/models/slack_deploy_hook_test.go

Currently, each deploy hook triggers upon a matching deploy hook. This PR adds a deduplication process, so that a given deployment won't send multiple messages to the same Slack channel or run the same GitHub Action multiple times the exact same way simultaneously.
This does _not_ worry about anything across multiple deployments (so concurrent deployments might run the same GHA concurrently or send messages to the same channel, but that's what we want).
This solves two important cases:
- Three chart releases in staging all have the same GHA configured as a deploy hook. The nightly dev -> staging currently causes it to be run three times. Now it'll just run once
- If you have one channel subscribed to messages for both alpha and staging, and something deploys to both environments …

[DDO-3430] Deduplicate deploy hook triggers

---

sherlock/internal/hooks/slack_deploy_hook.go

Removes an errant `. This is unfortunately from the part of the Slack hook codebase that doesn't have precise test coverage, but I think fixing the one-character typo is something we should just do rather than holding this up on trying to test this edge case.
Extremely low

[DDO-3440] Fix typo in message string

---

sherlock/internal/models/metrics_cron.go

Missed a `Preload("Environment")` when converting this code to the refactored world, which means that `chartRelease.Environment` is always nil, which means that the "environment_lifecycle" tag was never getting added to the chart release metrics. The accelerate metrics dashboard filters everything for that equaling "static", so that's why Mike noticed the dashboard being blank yesterday.
Also added some of the more recent data types to the data type count metrics.
Works locally. Testing this in an automatic way is very annoying because we don't really have any visibility into the OpenCensus library. Checked with Mike and he agreed that it's probably not worth it here.
Very low

[DDO-3444] Fix accelerate metrics

---

go-shared/pkg/utils/nil_or_call.go
go-shared/pkg/utils/nil_or_call_test.go
sherlock/internal/api/sherlock/chart_releases_v3.go
sherlock/internal/api/sherlock/chart_releases_v3_get.go
sherlock/internal/api/sherlock/chart_releases_v3_get_test.go
sherlock/internal/api/sherlock/chart_releases_v3_list.go
sherlock/internal/api/sherlock/chart_releases_v3_list_test.go
sherlock/internal/api/sherlock/chart_releases_v3_test.go
sherlock/internal/api/sherlock/environments_v3.go
sherlock/internal/api/sherlock/environments_v3_get.go
sherlock/internal/api/sherlock/environments_v3_get_test.go
sherlock/internal/api/sherlock/environments_v3_list.go
sherlock/internal/api/sherlock/environments_v3_list_test.go
sherlock/internal/api/sherlock/environments_v3_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/models/environment.go

Environment and ChartRelease GET endpoints, in refactored v3 format.
I noticed that the Pact UUID didn't make it into the new model type for environments, so I added it there too.
Lots. I did field-by-field for the data types back and forth, too.
Very low, new read-only endpoints.

[DDO-3449] Read-only ChartRelease/Environment API methods

---

sherlock/db/migrations/000076_block_duplicate_chart_releases.down.sql
sherlock/db/migrations/000076_block_duplicate_chart_releases.up.sql
sherlock/internal/api/sherlock/chart_releases_v3.go
sherlock/internal/api/sherlock/chart_releases_v3_create.go
sherlock/internal/api/sherlock/chart_releases_v3_create_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/deprecated_controllers/v2controllers/changeset.go
sherlock/internal/models/chart_release.go
sherlock/internal/models/chart_release_test.go
sherlock/internal/models/chart_release_version.go
sherlock/internal/models/environment.go
sherlock/internal/models/test_data.go

A variety of bug fixes and tests to stabilize the v3 chart release creation endpoint.
The largest fix is to properly block duplicate chart releases in the v3 world. This code here is used only when manually creating a specific chart release in al already-existing destination from Beehive.
There's also a minor fix stabilizing the sort order for v2 changesets. The increased load on the database from the added tests actually revealed that the return order for the embedded changelogs inside v2 changesets was unpredictable. Rather than make the tests for v2 changesets not care about the ordering -- the ordering does help readability in Beehive -- I added code to v2 changesets to stabilize the return order. We're about to remove the v2 code entirely (and the failure was _quite_ frequent, I …

[DDO-3449] Chart Release v3 create

---

sherlock/db/migrations/000077_block_duplicate_environments.down.sql
sherlock/db/migrations/000077_block_duplicate_environments.up.sql
sherlock/internal/api/sherlock/environments_v3.go
sherlock/internal/api/sherlock/environments_v3_create.go
sherlock/internal/api/sherlock/environments_v3_create_test.go
sherlock/internal/api/sherlock/environments_v3_test.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/models/environment.go
sherlock/internal/models/environment_test.go

Like #461 but for environments.
`namePrefix` is ngmi, that field was never actually used as far as I'm aware and it complicated things so much here (it wasn't persisted to the database!) that I'm just nuking it.
Yes
Low
There's a breaking change here... for parts of an API no one is using on a field that nothing is using. I still think this qualifies as low, if there's issues it'll come up in adopting the new APIs, not deploying them.

[DDO-3449] v3 environment create

---

sherlock/internal/api/sherlock/changesets_procedures_v3_chart_release_history.go
sherlock/internal/api/sherlock/changesets_procedures_v3_plan.go
sherlock/internal/api/sherlock/changesets_procedures_v3_plan_and_apply.go
sherlock/internal/api/sherlock/changesets_v3.go
sherlock/internal/api/sherlock/changesets_v3_list.go
sherlock/internal/api/sherlock/changesets_v3_test.go
sherlock/internal/api/sherlock/environments_v3.go

Fix one typo and one decidedly-not-typo in #467 that reared their head when generating the typed Go client in https://github.com/broadinstitute/sherlock/actions/runs/7830793055/job/21365702606.
The typo was me renaming a path parameter in the code but not fully in one of the Swagger comments. The other one was a type-system issue with query parameter parsing. In both cases, I think the Swagger page would've worked fine, but the Go client was getting type system issues, so here's a fix.
I also tweaked the string type for one of the fields to document it specifically a time field, rather than a plain string.

[DDO-3449] Resolve issues with the v3 changeset API in the Go client

---

sherlock/internal/api/sherlock/database_instances_v3_create.go
sherlock/internal/api/sherlock/database_instances_v3_edit.go
sherlock/internal/api/sherlock/database_instances_v3_upsert.go
sherlock/internal/api/sherlock/database_instances_v3_upsert_test.go
sherlock/internal/api/sherlock/routes.go

I thought that this wasn't used at all but it turns out I took a shortcut from Beehive that actually requires this. The easiest thing to do is basically make it just redirect to either the create handler or the edit handler. That requires a tiny bit of trickery to read the body twice but I think that's worth it to avoid adding indirection to the create and edit functions or duplicating code.
Added a test file, creates and edits are already tested
Very low

[DDO-3470] Add missing database instance method (upsert)

---

sherlock/internal/api/sherlock/pagerduty_integrations_v3_create.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_create_test.go

PagerdutyIntegration is a weird type because there's a field that is writable but not readable. A downstream effect in Beehive is that Beehive relied on upsert behavior that was provided by the generics in v2.
This PR adds similar-enough behavior to the pagerduty create endpoint so that Beehive won't run into edge cases using it.
Note that this isn't full upsert; it's a bit dumber than the slick behavior in #469, but that's not necessary here.
Added a test for the new behavior

[DDO-3470] Add missing PagerdutyIntegration upsert-ish behavior

---

sherlock/internal/api/sherlock/app_version_v3_list.go
sherlock/internal/api/sherlock/app_version_v3_list_test.go
sherlock/internal/api/sherlock/chart_releases_v3_delete.go
sherlock/internal/api/sherlock/chart_releases_v3_list.go
sherlock/internal/api/sherlock/chart_releases_v3_list_test.go
sherlock/internal/api/sherlock/chart_version_v3_list.go
sherlock/internal/api/sherlock/chart_version_v3_list_test.go
sherlock/internal/api/sherlock/charts_v3_delete.go
sherlock/internal/api/sherlock/charts_v3_list.go
sherlock/internal/api/sherlock/clusters_v3_delete.go
sherlock/internal/api/sherlock/clusters_v3_list.go
sherlock/internal/api/sherlock/database_instances_v3_delete.go
sherlock/internal/api/sherlock/database_instances_v3_list.go
sherlock/internal/api/sherlock/database_instances_v3_list_test.go
sherlock/internal/api/sherlock/environments_v3_delete.go
sherlock/internal/api/sherlock/environments_v3_list.go
sherlock/internal/api/sherlock/environments_v3_list_test.go
sherlock/internal/api/sherlock/incidents_v3_delete.go
sherlock/internal/api/sherlock/incidents_v3_list.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_delete.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_list.go
sherlock/internal/api/sherlock/users_v3_list.go

I messed up with copying and pasting some of the more basic endpoint implementations, and accidentally copied around a list implementation that didn't try to load associations (which makes sense for clusters but not for, say, chart releases).
This PR fixes that, everywhere, because I figure the consistency in source code is more important than any minuscule performance gains (if there's no associations Gorm won't actually send more over the wire).
I added tests for where the associative data actually shows up (there's some endpoints where this is a no-op)
Very low

[DDO-3470] Add missing association details in v3 list endpoints

---

sherlock/internal/api/sherlock/changesets_v3_list.go
sherlock/internal/api/sherlock/changesets_v3_list_test.go

So there doesn't seem to be a way to actually document `id=1&id=2&...` in Swaggo. Instead, if you do
```go
//	@param  id  query  []int  false  "Get specific changesets by their IDs, can be passed multiple times"
```
that actually means `id=1,2&...` which I definitely did not write code for. This seems consistent both from the gin-swagger page and from the generated typescript client. Whatever.
This fixes the issue; Sherlock will now handle either format and notes it does so in the OpenAPI spec.
Added cases to the unit tests for the new comma-separated format
Very low

[DDO-3470] Handle comma separated IDs better in Changeset requests

---

sherlock/internal/api/sherlock/app_version_procedures_v3_changelog.go
sherlock/internal/api/sherlock/chart_version_procedures_v3_changelog.go
sherlock/internal/models/app_version.go
sherlock/internal/models/app_version_test.go
sherlock/internal/models/changeset_plan_apply_test.go
sherlock/internal/models/chart_version.go
sherlock/internal/models/chart_version_test.go
sherlock/internal/models/test_data.go

Embarrassing bug with the directionality of changelogs. The database function was working fine, so the tests passed, but I was literally calling it with the IDs in the wrong order.
I changed the order of the arguments to what's more intuitive (db, fromID, toID) in my head and added tests for getting the directionality right.
I also modified the TestData to defer to the standard changelog capability, which is marginally slower but would've also caught this.
Modified tests both for the currently correct usage and the incorrect usage to get them aligned
Very low

[DDO-3470] Fix v3 changelog direction

---

.github/workflows/client-get-chart-release.yaml
.github/workflows/client-get-environment.yaml
.github/workflows/client-refresh-environment.yaml
.github/workflows/client-set-environment-app-version.yaml
.github/workflows/client-set-environment-chart-version.yaml

Thankfully here the APIs are directly compatible (nothing here uses deleteAfter or namePrefix or PUT methods, which are the only breaking changes)
I don't think it's necessary to make a half dozen PRs to some Terra service to test this given that app and chart version workflows have been using v3 endpoints for months without issue.
Here's the diffs one by one and the API they're set to contact:
```diff
-            "$SHERLOCK_PROD_URL/api/v2/chart-releases/${{ inputs.chart-release-name }}" \
+            "$SHERLOCK_PROD_URL/api/chart-releases/v3/${{ inputs.chart-release-name }}" \
```
https://sherlock.dsp-devops.broadinstitute.org/swagger/index.html#/ChartReleases/get_api_chart_releases_v3__selector_
```diff
-            "$SHERLOCK_PROD_URL/api/v2/environments/${{ inputs.environment-name …
```

[DDO-3470] Switch GHA workflows to use v3 endpoints

---

sherlock/internal/boot/middleware/logger.go

The kinds of madness we can do with Sherlock's authentication system. Six line diff including comments to log the workflow that made a given call to Sherlock.
I'm doing this to try to figure out what on earth is still calling Sherlock v2 endpoints.
Worked locally. Deployed to sherlock-dev and used the GitHub auth test action to issue a call to it from GHA, this showed up in the logs! Truncating everything else so I don't post IPs and stuff.
Very low

[DDO-3470] Add GitHub info to request logs when present

---

sherlock/internal/api/sherlock/changesets_procedures_v3_apply.go
sherlock/internal/api/sherlock/changesets_procedures_v3_chart_release_history.go
sherlock/internal/api/sherlock/changesets_procedures_v3_chart_release_history_test.go
sherlock/internal/api/sherlock/changesets_procedures_v3_version_history.go

Fixes https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1710166948331509?thread_ts=1710165100.662849&cid=CQ6SL4N5T and also https://broadinstitute.slack.com/archives/CQ6SL4N5T/p1710168821496979?thread_ts=1710165100.662849&cid=CQ6SL4N5T for good measure.
Added a failing test for the case Chelsea found. For the `uint` vs `[]uint` thing I don't even want to know how that was possible -- we literally have tests for that already -- and I'm choosing just to not spend extra time on it.
Low -- test case captures the issue Chelsea found and the behavior couldn't be much worse in that case anyway

[DDO-3534] Don't crash if requesting chart release version history when there's none

---

sherlock/db/migrations/000080_add_github_actions_jobs.down.sql
sherlock/db/migrations/000080_add_github_actions_jobs.up.sql
sherlock/docs/docs.go
sherlock/docs/swagger.json
sherlock/docs/swagger.yaml
sherlock/internal/api/sherlock/github_actions_jobs_v3.go
sherlock/internal/api/sherlock/github_actions_jobs_v3_get.go
sherlock/internal/api/sherlock/github_actions_jobs_v3_list.go
sherlock/internal/api/sherlock/github_actions_jobs_v3_upsert.go
sherlock/internal/api/sherlock/routes.go
sherlock/internal/models/github_actions_job.go

Adds a simple API to store GHA jobs with data on when they were queued, when they started, and when they completed. I'm not adding automated testing here, at least not right now -- Sherlock's tests will check that this won't break anything else, and I just want to move as quickly as possible to start collecting data.

[DDO-3577] API for GHA jobs

---

sherlock/internal/api/sherlock/slack_deploy_hooks_v3.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_create.go
sherlock/internal/api/sherlock/slack_deploy_hooks_v3_create_test.go

turns out that POST /api/deploy-hooks/slack/v3 wasn't actually parsing the mentionPeople field. PATCH was working so that's why we didn't really notice.
I just missed the field in the handler, one line fix
Added a test for the positive case, added validation of the existing negative case
Very low

[DDO-3609] Parse mentionBool upon creation

---

dev/local-with-pg.yaml
makefile
sherlock/db/README.md

Steps:
1. Add IAM database users for automated access and a built-in user for maintenance access (https://github.com/broadinstitute/terraform-ap-deployments/pull/1524)
2. Cut over codebase to IAM user and docs to maintenance user **<- We're here**
3. Remove other users from database
This PR updates docs to reference IAM database users and test harnesses to use Postgres 15, which is what we had to jump to for this change to work.
I'm jumping the shark a tiny bit here and just going ahead and mentioning the super-prod project name because we're only a few days away from that being correct.

[DDO-3625] Sherlock Database IAM Auth, Step 2 (Docs/Testing)

---

makefile

Tiny tweaks to deploy the proxy to super-prod instead. [broadinstitute/terraform-ap-deployments@`6ca3326` (#1527)](https://github.com/broadinstitute/terraform-ap-deployments/pull/1527/commits/6ca3326b93607e8e3f8286645273310766293141) gave this SA access to the new Sherlock

[DDO-3622] Deploy webhook proxy to super-prod instead

---

.github/workflows/client-get-chart-release.yaml
.github/workflows/client-get-environment.yaml
.github/workflows/client-refresh-environment.yaml
.github/workflows/client-report-app-version.yaml
.github/workflows/client-report-chart-version.yaml
.github/workflows/client-report-workflow.yaml
.github/workflows/client-set-environment-app-version.yaml
.github/workflows/client-set-environment-chart-version.yaml
.github/workflows/test-auth-transparency.yaml
sherlock-go-client/client/sherlock_client.go
sherlock-typescript-client/src/runtime.ts
sherlock-webhook-proxy/pkg/handler.go
sherlock/config/default_config.yaml
sherlock/docs/docs.go
sherlock/docs/swagger.json
sherlock/docs/swagger.yaml
sherlock/internal/boot/router.go
sherlock/internal/hooks/slack_deploy_hook_utils_test.go
sherlock/internal/models/ci_run.go
sherlock/internal/models/ci_run_test.go

Cutting over URLs, access SAs, and audiences in line with the new Sherlock and Beehive. This is a baby version of the Thelma PR that does most of the brunt work here.
See also:
- https://github.com/broadinstitute/thelma/pull/295
- https://github.com/broadinstitute/sherlock/pull/537
- https://github.com/broadinstitute/beehive/pull/467
- https://github.com/broadinstitute/terra-helmfile/pull/5471
- https://github.com/broadinstitute/terra-github-workflows/pull/189

[DDO-3622] Cut over URLs

---

dev/local-with-pg.yaml
sherlock/config/default_config.yaml
sherlock/config/test_config.yaml
sherlock/db/migrations/000083_add_suitability.down.sql
sherlock/db/migrations/000083_add_suitability.up.sql
sherlock/internal/api/sherlock/users_v3.go
sherlock/internal/api/sherlock/users_v3_list_test.go
sherlock/internal/authentication/authentication_method/enum.go
sherlock/internal/authorization/suitability.go
sherlock/internal/boot/application.go
sherlock/internal/models/boot.go
sherlock/internal/models/cluster.go
sherlock/internal/models/environment.go
sherlock/internal/models/pagerduty_integration.go
sherlock/internal/models/suitability.go
sherlock/internal/models/suitability_test.go
sherlock/internal/models/test_helper.go
sherlock/internal/models/test_helper_test.go
sherlock/internal/models/user.go
sherlock/internal/models/user_test.go
sherlock/internal/self/self.go
sherlock/internal/suitabilityloader/from_config.go
sherlock/internal/suitabilityloader/from_firecloud.go
sherlock/internal/suitabilityloader/sync_to_db.go

This PR is a bit awkward:
1. It adds a concept of Sherlock's own User -- as in, Sherlock will literally use ADC to figure out its own email and insert itself as a User into the database. This magic User is always understood to have super-user privileges (there's a safeguard to prevent accessing those magic privileges via a forged request or something).
2. It adds a table for Suitability. This table can only be edited by super-users (of which there are none right now except the aforementioned magic self User).
3. It adds a cronjob that shoves data into the Suitability table. This is basically copied from the existing mechanism -- copied including the lack of tests, because this is temporary code, we're sorta in construction mode right now (more info is in the ticket about how/why).
_And …

 [DDO-3673] Persistent suitability, part 1

---

sherlock/internal/api/sherlock/role_assignments_v3.go
sherlock/internal/api/sherlock/role_assignments_v3_create.go
sherlock/internal/api/sherlock/role_assignments_v3_create_test.go
sherlock/internal/api/sherlock/role_assignments_v3_edit.go
sherlock/internal/api/sherlock/role_assignments_v3_edit_test.go
sherlock/internal/api/sherlock/role_assignments_v3_list.go
sherlock/internal/api/sherlock/role_assignments_v3_list_test.go

@choover-broad pointed out that the timestamp API field was pretty difficult to work with from non-Go, because the duration is stored on the role as a Go duration (so other languages would need to emulate adding that duration to the current ISO-8601 time the way that Go can). Solution: add a calculated field at the API layer that just does that part. 
Added tests for the success and error cases of the new field
Low

[DDO-3714] RoleAssignment expiresIn

---

CONTRIBUTING.md

The GHA and branch protections are already in place, just documenting so I can link to this from the prod readiness checklist.

[DDO-3748] Document two reviewer rule

---

sherlock/config/default_config.yaml
sherlock/config/test_config.yaml
sherlock/go.mod
sherlock/go.sum
sherlock/internal/boot/router.go
sherlock/internal/middleware/cors/middleware.go
sherlock/internal/middleware/cors/middleware_test.go
sherlock/internal/middleware/csrf_protection/middleware.go
sherlock/internal/middleware/csrf_protection/middleware_test.go
sherlock/internal/middleware/headers/middleware_test.go

[Details in the ticket.](https://broadworkbench.atlassian.net/browse/DDO-3763)
This does the CORS thing that we've been having [the proxy do so far.](https://github.com/broadinstitute/terra-helmfile/blob/master/charts/sherlock/templates/configMap.yaml#L34-L40) Benefit now is that we can actually just pass the list of origins and it filters based on them, without treating them like a vulnerable regex like Apache does. Argument for this approach is that it's simpler.
We also move the CSRF mitigations from the proxy into Sherlock for the same reasons.
Two chart changes are required for this to work: we'll need to pass the origins into Sherlock's config and we'll need to configure the proxy to not mutate the Host/Origin headers so that this new middleware can see the real values.
Via unit …

[DDO-3763] Do CORS from Sherlock

---

sherlock/Dockerfile
sherlock/internal/api/sherlock/role_assignments_v3_create_test.go
sherlock/internal/models/role_assignment.go
sherlock/internal/models/role_assignment_test.go

Sarah Gibson found that it was possible for a user who could break-glass to break-glass for someone else who could not (because the permission function wasn't checking that the IDs matched).
Added a test for this exact mismatch case. Sarah confirmed that this resolved the issue.
Low

[DDO-3767] Check RoleAssignment mismatch

---

sherlock/config/default_config.yaml
sherlock/config/test_config.yaml
sherlock/internal/api/sherlock/role_assignments_v3.go
sherlock/internal/api/sherlock/role_assignments_v3_create.go
sherlock/internal/api/sherlock/role_assignments_v3_create_test.go
sherlock/internal/api/sherlock/role_assignments_v3_edit.go
sherlock/internal/api/sherlock/role_assignments_v3_edit_test.go
sherlock/internal/api/sherlock/roles_v3.go
sherlock/internal/boot/application.go
sherlock/internal/models/role.go
sherlock/internal/models/role_assignment.go
sherlock/internal/role_propagation/propagate.go
sherlock/internal/suitability_synchronization/load_from_config.go
sherlock/internal/suitability_synchronization/load_from_config_test.go
sherlock/internal/suitability_synchronization/load_from_firecloud.go
sherlock/internal/suitability_synchronization/load_into_db.go
sherlock/internal/suitability_synchronization/suspend_role_assignments.go
sherlock/internal/suitability_synchronization/suspend_role_assignments_test.go

Three steps:
1. Refactors existing suitability loading to be in a suitability synchronization package
2. Adds a cronjob-type-thing to automatically suspend role assignments that should be suspended
3. Adjusts API to enforce the "calculated field" of role assignment suspension
The usual test coverage. Went a little bit overboard with some of the API level tests
Low

[DDO-3772] Add automatic suspension

---

sherlock/db/migrations/000062_environment_v3.up.sql
sherlock/db/migrations/000092_required_role.down.sql
sherlock/db/migrations/000092_required_role.up.sql
sherlock/internal/api/sherlock/clusters_v3.go
sherlock/internal/api/sherlock/clusters_v3_create.go
sherlock/internal/api/sherlock/clusters_v3_create_test.go
sherlock/internal/api/sherlock/clusters_v3_edit.go
sherlock/internal/api/sherlock/clusters_v3_list.go
sherlock/internal/api/sherlock/environments_v3.go
sherlock/internal/api/sherlock/environments_v3_test.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_create_test.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_delete_test.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_edit_test.go
sherlock/internal/api/sherlock/pagerduty_integrations_v3_list_test.go
sherlock/internal/models/cluster.go
sherlock/internal/models/cluster_test.go
sherlock/internal/models/environment.go
sherlock/internal/models/environment_test.go
sherlock/internal/models/pagerduty_integration.go
sherlock/internal/models/pagerduty_integration_test.go
sherlock/internal/models/role_assignment.go
sherlock/internal/models/role_assignment_test.go
sherlock/internal/models/test_data.go
sherlock/internal/models/user.go
sherlock/internal/models/user_test.go

1. PagerdutyIntegration: `User.ErrIfNotSuitable()` -> `User.ErrIfNotSuperAdmin()` (replaces suitability check with super-admin check, since we're the only ones that can use those endpoints anyway)
2. Environment: `User.ErrIfNotSuitable()` + `User.ErrIfNotActiveInRole()` (adds role check if new `required_role_id` column is filled; existing `requires_suitability` column still respected)
3. Cluster: `User.ErrIfNotSuitable()` + `User.ErrIfNotActiveInRole()` (adds role check if new `required_role_id` column is filled; existing `requires_suitability` column still respected)
Once this is fully rolled out I'll do a follow-up change to clean up the remaining usages of `User.ErrIfNotSuitable()`
Adjusted lots of tests to get coverage here but in theory this is totally additive. The test data was …

[DDO-3776] Check role membership

---

sherlock/internal/api/sherlock/users_v3_upsert.go
sherlock/internal/api/sherlock/users_v3_upsert_test.go

Adds an additional notification coming from the User upsert endpoint to better broadcast account linking information.
Mocked tests updated
Very low

[DDO-3781] Improve account linking notification

---

sherlock/internal/api/sherlock/clusters_v3.go
sherlock/internal/api/sherlock/clusters_v3_edit.go
sherlock/internal/api/sherlock/clusters_v3_edit_test.go
sherlock/internal/api/sherlock/environments_v3.go
sherlock/internal/api/sherlock/environments_v3_edit.go
sherlock/internal/api/sherlock/environments_v3_edit_test.go

In developing the UI for configuring Environments and Clusters with a required Role I realized that it wasn't possible to clear out the field once it was set. Hello Go.
This fix manually clears out the field when an edit request is made with it set to an empty string. This is what the UI will already do so there's no changes to that (upcoming) PR.
Unit test for both Environments and Clusters
Low

[DDO-3776] Allow clearing role requirement

---

sherlock/db/migrations/000094_add_enable_janitor.down.sql
sherlock/db/migrations/000094_add_enable_janitor.up.sql
sherlock/internal/api/sherlock/environments_v3.go
sherlock/internal/api/sherlock/environments_v3_test.go
sherlock/internal/models/environment.go

Adds an editable boolean field to Environment, "enableJanitor". BEEs default to template, template envs default to true, static envs default to false. DB migration sets fields that way for all existing environments.
Added to existing field input/output tests
Very low

[DDO-3789] Enable Janitor Toggle

---

.github/workflows/sherlock-container-scan.yaml

for appsec. We automatically move the `:latest` tag in sherlock-build.yaml so we can just have this workflow use it rather than trying to read version data from Sherlock or something more complex.
Added push trigger temporarily, [it ran.](https://github.com/broadinstitute/sherlock/actions/runs/10098933680/job/27927018804?pr=612)
Very low.

[DDO-3793] Weekly Container Scan

---

.github/workflows/sherlock-build.yaml
sherlock/config/default_config.yaml
sherlock/internal/oidc_models/storage.go
sherlock/internal/oidc_models/storage_test.go

- Update docs to explain how the OIDC issuer URLs are used now, because the setup we landed on is a bit different than what the docs I wrote anticipated
- Base64 encode the random bytes used for refresh tokens. We don't bother decoding (that way Sherlock will still respect previously-generated refresh tokens); it's that this way the refresh tokens Sherlock returns are safer to store in yaml files like ArgoCD wants to do
Added test for refresh token being b64
Very low

[DDO-3785] Update OIDC docs and b64 encode refresh tokens

---

.github/workflows/sherlock-build.yaml
sherlock/config/default_config.yaml
sherlock/internal/api/sherlock/clusters_v3_create_test.go
sherlock/internal/api/sherlock/clusters_v3_delete_test.go
sherlock/internal/api/sherlock/clusters_v3_edit_test.go
sherlock/internal/api/sherlock/environments_v3_create_test.go
sherlock/internal/api/sherlock/environments_v3_edit_test.go
sherlock/internal/models/cluster.go
sherlock/internal/models/cluster_test.go
sherlock/internal/models/environment.go
sherlock/internal/models/environment_test.go
sherlock/internal/models/user.go
sherlock/internal/oidc_models/storage.go
sherlock/internal/oidc_models/storage_test.go

I'll remove it from the API and then the database at a later junction. Requires all other PRs for DDO-3785 to be merged first.
Updated tests to all reference roles rather than suitability. Had more than I thought, I thought I updated tests before, but I'm not arguing.
Low

[DDO-3785] Ignore suitability within Sherlock

---

sherlock/config/default_config.yaml
sherlock/docs/docs.go
sherlock/docs/swagger.json
sherlock/docs/swagger.yaml
sherlock/internal/boot/router.go

Making a fully valid Swagger spec from Sherlock's dynamic doc.json endpoint helps appsec's tools run against it. We'll need to specify the primaryHost from helmfile. Can't borrow origins here because origins is a list for use with CORS, and those have schemes anyway.
Also adds `/` as a base path. I've confirmed on the Swagger page that there's no difference in behavior here. Since doc.json sets basepath to an empty string if you don't provide it, that too was failing some validation.
Setting basepath to `/` is the same as what should be done automatically: https://swagger.io/docs/specification/2-0/api-host-and-base-path/
It's okay for this to ship immediately because the empty primaryHost value is the same behavior as we've got right now.
I used the Swagger page generated on this PR and …

[DDO-3829] Document host on Swagger page

---

sherlock/internal/suitability_synchronization/suspend_role_assignments.go
sherlock/internal/suitability_synchronization/suspend_role_assignments_test.go

Right now it sends three notifications per change per channel -- "modified role assignments based on suitability" (expected), "created User" (???), "edited RoleAssignment ..." (expected).
Turns out it's our friend, Gorm's automatic upsert of associations. Gotta do the usual `Omit(clause.Associations)`.
Modified the mocked test for this function to enforce a specific count of the notifications that are sent. The test now fails without this fix.
Very low

[DDO-3828] Remove spurious notifications when suspending role assignments

---

sherlock/internal/api/sherlock/changesets_procedures_v3_plan.go
sherlock/internal/api/sherlock/changesets_procedures_v3_plan_test.go
sherlock/internal/models/chart_release_version.go
sherlock/internal/models/chart_release_version_test.go

To resolve https://broadinstitute.slack.com/archives/CADU7L0SZ/p1723044063825579 and https://broadinstitute.slack.com/archives/CADM7MZ35/p1722878301943999, add an option to Changeset Environment entries `filterToMatchingBranches` which will omit app version promotions if there's a branch mismatch.
This requires the repos to properly report app versions to Sherlock, but it's better than nothing. We can set this to true in [the automatic promotion to staging](https://github.com/broadinstitute/terra-github-workflows/blob/main/.github/workflows/staging-promotion.yaml#L83) and it'll block the issue that we've seen.
Added an exact test for both sides of this flag; existing tests thoroughly check against regressions
Low

[DDO-3831] Add Changeset filterToMatchingBranches

---

sherlock/config/default_config.yaml

The previous config would've propagated roles to people's BI Microsoft accounts, but Mike and I think that test.firecloud.org / firecloud.org is actually what we want here.
Role propagation can handle this change so I'm not calling this breaking.
This is a default config tweak -- there's existing tests for how this suffix gets used and substituted
Low

[DDO-3854] Propagate to FC Microsoft accounts

---

sherlock/config/default_config.yaml

Typo in Sherlock's default config

[DDO-3853] Reference "quality.firecloud.org" not "qa.firecloud.org"

---

sherlock/internal/firecloud_account_manager/suspend_accounts.go
sherlock/internal/firecloud_account_manager/suspend_accounts_test.go

An impressive thing to forget when writing this code but whatever. Before it would've just repeatedly kept suspending people which would've flooded us with notifications (as in, it would've sent one ever hour).
Modified test cases
Very low (security impact non-zero but we haven't even turned this on, and again, the actual functionality would've been okay, it just would've notified us too much)

[DDO-3857] Firecloud account manager: ignore suspended users

---

sherlock/internal/boot/application.go
sherlock/internal/clients/slack/permission_change_notification.go
sherlock/internal/clients/slack/permission_change_notification_test.go
sherlock/internal/models/role_assignment.go
sherlock/internal/models/role_assignment_auto_expire.go
sherlock/internal/models/role_assignment_auto_expire_test.go
sherlock/internal/role_propagation/propagate.go
sherlock/internal/role_propagation/propagate_test.go
sherlock/internal/role_propagation/propagator_propagate.go
sherlock/internal/role_propagation/propagator_propagate_test.go
sherlock/internal/suitability_synchronization/suspend_role_assignments.go
sherlock/internal/suitability_synchronization/suspend_role_assignments_test.go

- Dedupe some Slack notifications to avoid spam in the security events channel
- Automatically expire-by-deletion role assignments to agree better with Beehive's prod access button
- Summarize role assignments better in Slack
Mocked tests have been updated/added
Low

[DDO-3862] Prep for breakglass setup

---

sherlock/internal/suitability_synchronization/suspend_role_assignments.go
sherlock/internal/suitability_synchronization/suspend_role_assignments_test.go

I got my wires crossed with how to assemble the context here and tests didn't catch it. Updates tests and uses the right context.
Updated
Low

[DDO-3863] Fix notification context for suspending users

---

sherlock/internal/models/role.go
sherlock/internal/models/role_assignment.go

...by stopping Gorm's upsert-associations-by-default behavior when creating the database journal rows.
I've already got tests ensuring that the rows get created. This upsert is "safe" because it's in-transaction journaling, but it was running hooks unnecessarily. Unnecessary hooks are fine when it's quiet... but these ones are not. It runs the create hook, so it's erroneously telling us that it's being created when it isn't.
We've got tests that notifications get sent and journal rows get created. We test the functionality we need -- we're just removing some extra cycles that were cruft.
Low

[DDO-3865] Remove spurious notifications for Role/RoleAssignments

---

sherlock/internal/api/sherlock/ci_runs_v3_upsert.go
sherlock/internal/api/sherlock/ci_runs_v3_upsert_test.go
sherlock/internal/models/ci_run.go
sherlock/internal/models/ci_run_test.go

From DCJ's channel:
This PR makes two improvements:
1. Carry forward any custom icon set on a previous run, the same way we do for retry notification channels. Put differently, this fixes #533 to be aware of #442.
2. Note in Slack messages when a retry is a retry, i.e. "jade-data-repo-ui's test-unit workflow (attempt 2): [success](https://github.com/DataBiosphere/jade-data-repo-ui/actions/runs/10823918604/attempts/2)"
Tests for both components updated to get full coverage
Very low

[DDO-3874] CiRun retry Slack message improvements

---

sherlock/go.mod
sherlock/go.sum
sherlock/html/close.html
sherlock/html/close.js
sherlock/html/html.go
sherlock/html/html_test.go
sherlock/internal/boot/router.go
sherlock/internal/middleware/security/middleware.go
sherlock/internal/middleware/security/middleware_test.go

Adds a Content-Security-Policy header to Sherlock's responses. A lot of Terra services got a ticket filed -- I think Sherlock hasn't yet but it's vulnerable in the same way. I did a research project on CSPs in college so I figured I'd just knock this out since I had a minute while working on other stuff. Changes:
1. Bump gin-swagger from 1.6.0 to v1.6.1-0.20231210095754-aa92a0ac3f26 (on master) to include the merged-but-not-yet-released https://github.com/swaggo/gin-swagger/pull/280 that makes the Swagger page much much more compatible with CSPs. Dependabot still understands what's going on here so when it does become released we'll get it for free.
2. Change the close.html file to have the Javascript in a separate close.js file, again to make it much more compatible with CSPs.
3. Pull in …

[DDO-3889] Content Security Policy

---

sherlock/internal/clients/slack/deployment_notification.go
sherlock/internal/clients/slack/permission_change_notification.go
sherlock/internal/clients/slack/permission_change_notification_test.go

Gets rid of the "Sherlock error: invalid blocks" message that pops up in the security events channel whenever Sherlock makes a ton of changes at once. This is the same approach that's worked for deployment changelog notifications, but it's handled a bit differently for reasons explained inline.
This is split out from the main "meat" of DDO-3890 because the rest of it is high risk but this is very low risk.
Tests updated to capture this exact behavior with mocks.
Very low.

[DDO-3890] Chunk permission change notifications

---

sherlock/go.mod
sherlock/go.sum
sherlock/internal/boot/router.go
sherlock/internal/middleware/security/middleware.go
sherlock/internal/middleware/security/middleware_test.go

So swagger-ui is vulnerable. We don't directly rely on it. We rely on github.com/swaggo/files, which _submodules in_ swagger-ui. Javascript code but not through npm. I'm not kidding -- that took a minute to figure out.
So anyway, looks like someone bumped the v2 branch of swaggo/files to have a non-vulnerable swagger-ui a few months back. But the v2 branch of swaggo/files is incompatible with swaggo/gin-swagger. Ugh. So we have to adapt the `fs.FS` that swaggo/files now provides with the `webdav.FileSystem`/`webdav.Handler` that swaggo/gin-swagger expects. It's not that bad because it's just a stub.
Fun fact, the newer swagger-ui now uses React to apply inline styles imperatively. So it started failing Sherlock's hash-based CSP. _Whatever_. Sarah Gibson directly confirmed that including …

[DDO-3907] Update swagger-ui

---

sherlock/db/migrations/000101_chart_name_validation.down.sql
sherlock/db/migrations/000101_chart_name_validation.up.sql
sherlock/internal/models/chart_test.go

Sherlock checks that the chart name isn't empty, but it doesn't impose validation on it not having special characters. This is a problem when security scanners target Sherlock's API, because "garbage in garbage out" means Sherlock ingests and stores the garbage.
This PR changes the validation to not just check emptiness but also that it matches the same kind of regex we use to validate environment names.
It is possible for deployment of this change to fail if there's already garbage in the database. I've checked and prod doesn't suffer from this. Dev does so I'll clean up manually.
```sql
delete from charts where name not similar to '[a-z0-9]([-a-z0-9]*[a-z0-9])?';
```
We have a ton of testing for all sorts of valid chart names; everything in TestData gets automatically created. I added a …

[DDO-3911] improve chart name validation

---

sherlock/internal/api/sherlock/environments_v3_edit.go
sherlock/internal/api/sherlock/environments_v3_edit_test.go

In #713 I missed an edge case, where trying to clear the banner bucket sets the db value to the empty string instead of null.
Tests added for this case and I verified with local Sherlock + Beehive.

[DDO-3900] Fix clearing banner bucket

---

.github/workflows/sherlock-check-api-diff.yaml

This action appears to be broken in several dependabot PRs; turns out https://github.com/char0n/swagger-editor-validate/ has moved to https://github.com/char0n/swagger-editor-validate/.

[DDO-4044] Use official swaggerexpert/swagger-editor-validate action

---

sherlock/Dockerfile
sherlock/go.mod
sherlock/go.sum

https://broadworkbench.atlassian.net/browse/DDO-4029
- Revert upgrades in #800 
- Upgrade go-jose (and necessary libraries) to fix security finding

DDO-4029 revert upgrades except go-jose
